import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {AIService,localEndpoint,validateProposal} from '../ai.mjs';import {createCharacter} from '../public/engine.mjs';
const response=content=>({ok:true,text:async()=>JSON.stringify({choices:[{message:{content}}],usage:{total_tokens:42}})});
test('local endpoints reject remote URLs, secrets and redirect destinations',()=>{assert.equal(localEndpoint('http://127.0.0.1:11434/v1'),'http://127.0.0.1:11434/v1');for(const url of ['https://example.com/v1','http://user:pass@localhost/v1','file:///etc/passwd','http://localhost/v1?key=x'])assert.throws(()=>localEndpoint(url));});
test('AI cannot invent state mutations or unsupported actions',()=>{const s=createCharacter();assert.throws(()=>validateProposal({action:'gain:10000',hp:999},s));assert.deepEqual(validateProposal({clarification:'Which person?'},s),{clarification:'Which person?'});});
test('mock provider: bounded context, usage, valid interpretation and narration',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{let sent;const ai=new AIService({dir,fetcher:async(url,args)=>{sent=JSON.parse(args.body);assert.equal(args.redirect,'error');return response('{"action":"explore","reason":"Inspect the gate"}');}});const result=await ai.request({mode:'local',kind:'propose',model:'test',state:createCharacter(),text:'look around'});assert.equal(result.action,'explore');assert.equal(sent.max_tokens,600);assert.equal(result.usage.requests,1);assert.equal(result.usage.tokens,42);assert.ok(sent.messages[1].content.length<15000);}finally{await rm(dir,{recursive:true,force:true});}});
test('outage and malformed provider output preserve game state; manual retry succeeds',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{let count=0;const ai=new AIService({dir,fetcher:async()=>{count++;if(count===1)throw Error('Connection refused');if(count===2)return response('not json');return response('{"action":"explore"}');}});const state=createCharacter(),before=JSON.stringify(state),body={mode:'local',kind:'propose',model:'test',state};await assert.rejects(ai.request(body),/Connection refused/);await assert.rejects(ai.request(body),/malformed/);assert.equal((await ai.request(body)).action,'explore');assert.equal(JSON.stringify(state),before);assert.equal((await ai.status()).requests,3);}finally{await rm(dir,{recursive:true,force:true});}});
test('cancel propagates to model and concurrent requests are rejected',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{let ready;const started=new Promise(r=>ready=r);const ai=new AIService({dir,fetcher:async(u,args)=>{ready();return new Promise((resolve,reject)=>{args.signal.addEventListener('abort',()=>reject(new DOMException('Cancelled','AbortError')));});}});const controller=new AbortController(),body={mode:'local',kind:'test',model:'test'};const running=ai.request(body,controller.signal);await started;await assert.rejects(ai.request(body),/already running/);controller.abort();await assert.rejects(running,{name:'AbortError'});assert.equal(ai.busy,false);}finally{await rm(dir,{recursive:true,force:true});}});
test('online spending remains disabled with no credentials',async()=>{const ai=new AIService({env:{}});await assert.rejects(ai.request({mode:'online',kind:'test'}),/disabled/);});
test('immersive AI maps an open-ended action to a checked approach and carries speech tone',()=>{const s=createCharacter();const result=validateProposal({action:'improvise:persuade',tone:'kind',reason:'Make a reasoned case'},s);assert.equal(result.action,'improvise:persuade');assert.equal(result.tone,'kind');assert.throws(()=>validateProposal({action:'attack',combo:['unknown']},s));});

test('local Qwen3 API requests disable thinking without changing generic prompts',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{const sent=[];const ai=new AIService({dir,fetcher:async(u,args)=>{sent.push(JSON.parse(args.body));return response('Connection ready.');}});for(const model of ['qwen/qwen3-8b','generic-model','qwen/qwen3.5-9b'])await ai.request({mode:'local',kind:'test',model});assert.equal(sent[0].reasoning_effort,'none');assert.equal(sent[2].reasoning_effort,'none');assert.equal(sent[1].reasoning_effort,undefined);assert.match(sent[0].messages[0].content,/\/no_think$/);assert.doesNotMatch(sent[1].messages[0].content,/\/no_think/);}finally{await rm(dir,{recursive:true,force:true});}});
test('reasoning-only output is never returned as narration and gives actionable feedback',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{const ai=new AIService({dir,fetcher:async()=>({ok:true,text:async()=>JSON.stringify({choices:[{finish_reason:'length',message:{content:'',reasoning_content:'internal reasoning'}}]})})});await assert.rejects(ai.request({mode:'local',kind:'test',model:'qwen/qwen3-8b'}),/no final answer.*Disable Thinking/);}finally{await rm(dir,{recursive:true,force:true});}});

test('local development bypasses paid cap while online retains its independent limit',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{await writeFile(path.join(dir,'usage.json'),JSON.stringify({day:new Date().toISOString().slice(0,10),requests:30,tokens:100}));const ai=new AIService({dir,env:{ENABLE_ONLINE_AI:'true',ONLINE_API_KEY:'test-only',ONLINE_MODEL:'mock',AI_DAILY_REQUESTS:'30'},fetcher:async()=>response('Connection ready.')});const local=await ai.request({mode:'local',kind:'test',model:'qwen/qwen3.5-9b'});assert.equal(local.usage.limit,null);assert.equal(local.usage.requests,1);assert.equal((await ai.status('online')).requests,30);await assert.rejects(ai.request({mode:'online',kind:'test'}),/cap reached/);for(let i=0;i<32;i++)await ai.request({mode:'local',kind:'test',model:'test'});assert.equal((await ai.status()).requests,33);assert.equal((await ai.status('online')).requests,30);}finally{await rm(dir,{recursive:true,force:true});}});
test('late provider reply after cancellation is discarded',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'vp-test-'));try{const controller=new AbortController();const ai=new AIService({dir,fetcher:async()=>{controller.abort();return response('Late reply');}});await assert.rejects(ai.request({mode:'local',kind:'test',model:'test'},controller.signal),{name:'AbortError'});}finally{await rm(dir,{recursive:true,force:true});}});
