import test from 'node:test';import assert from 'node:assert/strict';
import {createCharacter,act,encode,decode,legalActions,context,validateSave} from '../public/engine.mjs';
import {personalArcs,arcState} from '../public/bonds.mjs';
import {factions,techniques} from '../public/world.mjs';
import {continueJourney} from '../public/sandbox.mjs';
const go=(s,p)=>s.location===p?s:act(s,'travel:'+p);
for(const f of factions)for(const choice of ['loyal','other'])test(`${f.id}: ${choice} personal arc completes once, records consequences and reloads`,()=>{
 let s=go(createCharacter({seed:'bonds',build:{martial:'none'}}),f.place);s=act(s,'talk:'+f.id);s=act(s,`bond:${f.id}:open`);assert.throws(()=>act(s,`bond:${f.id}:${choice}`));s=go(s,personalArcs[f.id].place);s=act(s,`bond:${f.id}:investigate`);s=decode(encode(s));s=go(s,f.place);const coins=s.coins,trust=s.relationships[f.id];s=act(s,`bond:${f.id}:${choice}`);assert.equal(s.relationships[f.id],trust+(choice==='loyal'?2:-2));assert.equal(s.coins,coins+(choice==='other'?8:0));assert.equal(arcState(s,f.id),choice==='loyal'?'bonded':'estranged');assert.ok(s.memories[f.id].at(-1).includes('The traveler chose'));assert.throws(()=>act(s,`bond:${f.id}:${choice}`));if(choice==='other')assert.ok(!legalActions(s).includes('learn:'+techniques.find(t=>t.faction===f.id).id));assert.deepEqual(decode(encode(s)),s);
});
test('unrevealed personal evidence is excluded from narrator context',()=>{let s=createCharacter();assert.ok(!JSON.stringify(context(s)).includes(personalArcs.jade.discovery));s=go(s,'clinic');s=act(s,'talk:jade');s=act(s,'bond:jade:open');assert.ok(!JSON.stringify(context(s)).includes(personalArcs.jade.discovery));s=go(s,'tribunal');s=act(s,'bond:jade:investigate');assert.ok(JSON.stringify(context(s)).includes(personalArcs.jade.discovery));});
test('unfinished request continues through letters without teleporting its NPC',()=>{let s=createCharacter();s=act(s,'talk:ash');s=act(s,'bond:ash:open');s=act(s,'end:wander');s=continueJourney(s);s=go(s,'market');s=act(s,'bond:ash:investigate');assert.throws(()=>act(s,'bond:ash:loyal'));s=go(s,'shrine');s=act(s,'bond:ash:loyal');assert.match(s.journal.findLast(e=>e.kind==='dialogue').text,/writes:/);assert.ok(!context(s).npcs.some(n=>n.name.includes('Kao Ren')));assert.equal(arcState(decode(encode(s)),'ash'),'bonded');});
test('no remote request, no partial qi spending, and corrupt arc state rejected',()=>{let s=createCharacter();assert.throws(()=>act(s,'bond:jade:open'));s=act(s,'talk:ash');s=act(s,'bond:ash:open');s=go(s,'market');s.qi=1;const before=structuredClone(s);assert.throws(()=>act(s,'bond:ash:investigate'));assert.deepEqual(s,before);s.flags['arc:ash']='invented';assert.throws(()=>validateSave(s));});

test('reassurance does not erase an estranged expression or teaching boundary',()=>{let s=go(createCharacter(),'clinic');s=act(s,'talk:jade');s=act(s,'bond:jade:open');s=go(s,'tribunal');s=act(s,'bond:jade:investigate');s=go(s,'clinic');s=act(s,'bond:jade:other');s=act(s,'talk:jade',{text:'I want to help. You can trust me.'});assert.equal(s.flags['mood:jade'],'hostile');assert.ok(!legalActions(s).includes('learn:seal'));});
