import test from 'node:test';import assert from 'node:assert/strict';
import {createCharacter,act,decode,encode,validateSave,options} from '../public/engine.mjs';
import {worldFor,encounter} from '../public/procedural.mjs';
import {continueJourney,regionName} from '../public/sandbox.mjs';
test('world generation is reproducible by seed and differs between seeds',()=>{assert.deepEqual(worldFor('reed'),worldFor('reed'));assert.notDeepEqual(worldFor('reed'),worldFor('ash'));const s=createCharacter({seed:'reed'});assert.deepEqual(decode(encode(s)).world,s.world);});
test('generated encounter rewards cannot repeat and recurring identities remember',()=>{let s=createCharacter({seed:'reed'});const person=s.world.people[0];if(s.location!==person.home)s=act(s,'travel:'+person.home);const e=encounter(s);assert.ok(e);s=act(s,'event:leave');assert.ok(s.world.people[0].memories.length);assert.equal(encounter(s),null);assert.throws(()=>act(s,'event:leave'));validateSave(s);});
test('chapter endings continue into renewable districts without losing character',()=>{let s=createCharacter({seed:'long-road'});const stats={...s.stats};s=act(s,'end:wander');s=continueJourney(s);assert.equal(s.chapter,2);assert.equal(s.ending,null);assert.deepEqual(s.stats,stats);assert.ok(options(s).some(o=>o.id==='road'));for(let i=0;i<20;i++){s=act(s,'improvise:labor',{text:'I find honest work carrying freight.'});s=act(s,'road');validateSave(s);s=decode(encode(s));}assert.equal(s.chapter,22);assert.ok(s.coins>16);assert.ok(Object.keys(s.contacts).length>=4);assert.match(regionName(s),/District/);});
test('open-ended attempts resolve through costs and checks, not arbitrary rewards',()=>{let s=createCharacter({seed:'sandbox'});const before=s.coins;s=act(s,'improvise:craft',{text:'I prepare a field remedy.'});assert.equal(s.coins,before-2);assert.equal(s.time,2);assert.ok(s.facts.at(-1).includes('field remedy'));assert.equal(s.maxHp,32);assert.throws(()=>act(s,'improvise:become-a-god'));});
test('generated road combat rewards are separate from the fever ledger',()=>{let s=createCharacter({seed:'fighter',build:{body:'iron',affinity:'cinder',qigong:'iron'}});s=act(s,'improvise:challenge',{text:'I challenge a road swordsman.'});assert.equal(s.combat.sandbox,true);while(s.combat&&!s.ending)s=act(s,'attack');assert.ok(!s.flags.ledger);assert.ok(!s.ending);assert.ok(s.insight>=2);validateSave(s);});
