import {factions,places} from './world.mjs';
export const personalArcs={
 jade:{title:'The signature beneath the seal',place:'tribunal',task:'Copy the quarantine order',opening:'Shen asks for a certified copy of the quarantine order. “Read the signature before you decide what you owe me.”',discovery:'The order bears Shen’s signature. She authorized passage before the cargo was inspected. A marginal note records her objection, filed too late.',loyal:'Demand her public testimony',other:'Sell the copy to her opponents',reply:'“I will answer under my own name. Do not make me innocent to make this easier.” Shen sends her signed deposition.',refusal:'“You had every right to accuse me. Selling the accusation is a different profession.” Shen closes her private correspondence.',rival:'ash'},
 ash:{title:'Pay for the living',place:'market',task:'Audit the veterans’ pay chest',opening:'Kao has found wages owed to dead guards. Their captain wants the money returned. Kao wants their families paid. “Find out how much is left.”',discovery:'The pay clerk has enough for the families, but releasing it without a countersignature will make Kao personally liable.',loyal:'Pay the families under Kao’s name',other:'Return the chest for a finder’s fee',reply:'“The captain has my name. The families have their supper. I can live with that.” Kao includes a child’s crooked thank-you note.',refusal:'“A receipt is a clean thing. Hunger isn’t. Keep yours.” Kao will discuss business, but no longer his family.',rival:'jade'},
 veil:{title:'An echo is not a prophecy',place:'sluice',task:'Measure the hidden resonance',opening:'Bai hears young listeners selling certainty to frightened people. She asks you to measure the sluice echo. “Bring me what happens, not what you wish it means.”',discovery:'The same bell sounds different when the sluice gate opens. Water and stone explain the omen. A patron would pay well to keep the miracle alive.',loyal:'Publish the measured explanation',other:'Sell the miracle to its patron',reply:'“Three pupils left when I told them. Two stayed to listen again. Two is a beginning.” Bai sends the corrected measurements.',refusal:'“You heard a mechanism and sold a god. I will not lend you my voice.” Bai refuses further private lessons.',rival:'masks'},
 river:{title:'The passenger without a name',place:'clinic',task:'Find the missing passenger record',opening:'Qiao asks after a woman removed from an old ferry list. “My daughter lived because I gave someone a name. Someone else’s daughter did not come home.”',discovery:'The clinic record identifies the survivor and the debt Qiao has been quietly paying. Publishing her name would expose the life she rebuilt.',loyal:'Carry his apology without naming her',other:'Sell the passenger list to creditors',reply:'“She did not forgive me. She accepted the letter. That is hers to decide.” Qiao leaves a lantern burning without asking you to praise him.',refusal:'“I trusted you with the part I could not repair. Now there are two of us who sold her name.” His next letter is returned unopened.',rival:'star'},
 furnace:{title:'A stamp on every shackle',place:'sluice',task:'Take an impression of the lock stamp',opening:'Du wants proof that her furnace stamp was copied onto prison fittings. “If it is mine, say so. If it is stolen, prove it.”',discovery:'The impression matches Du’s old die. Her guild reused it after she withdrew the design. Breaking the die will cost her the guild contract.',loyal:'Return the proof and break the die',other:'Sell the design back to the guild',reply:'“Contract gone. Stamp broken. My apprentice asked whether we can afford honesty. I told her we will learn.” Du encloses a plain maker’s mark.',refusal:'“You found the chain and ordered another length.” Du will sell ordinary tools, but refuses her private craft.',rival:'bone'},
 masks:{title:'An understudy’s real name',place:'tribunal',task:'Collect the sealed witness summons',opening:'Mian’s clerk-informant has been summoned publicly. “The truth wants a face. I would prefer it did not consume the person wearing it.”',discovery:'The summons offers immunity only if the informant names every accomplice. An anonymous deposition can protect the clerk, but weakens the public case.',loyal:'Protect the witness’s identity',other:'Sell the witness’s name to the court',reply:'“An imperfect performance. A living actor. For once I prefer that order.” Mian sends a letter without a borrowed signature.',refusal:'“You have supplied the court with its final act. Do not ask me to applaud.” Mian removes you from the trusted cast.',rival:'veil'},
 bone:{title:'The name on the other side',place:'gate',task:'Recover the enemy casualty list',opening:'Anwei wants a dead enforcer included among the fever victims. The families object. “His crimes belong in the record. So does his name.”',discovery:'The guard list gives the enforcer a name and a surviving mother. The burial committee will pay to remove him from the memorial.',loyal:'Record his name and his crimes',other:'Take payment to erase his name',reply:'“His mother came. So did a woman he hurt. Neither asked the other to leave.” Anwei sends both testimonies, separately bound.',refusal:'“You have learned to count the worthy dead. I asked you to remember people.” Anwei still offers public care, but withdraws her confidence.',rival:'furnace'},
 star:{title:'The price of an empty wagon',place:'ferry',task:'Check the refugees’ passage accounts',opening:'Yao’s investors want payment for seats she gave to refugees. “I can lose a route. My drivers cannot lose a season’s wages. Check the accounts.”',discovery:'The passenger accounts show the crew accepted delayed wages. The shareholders will waive the loss if Yao identifies the refugees as debtors.',loyal:'Back the crew’s refusal to collect',other:'Sell the debtor accounts',reply:'“Lost two investors. Kept every driver. Ask me in winter whether that was wise.” Yao sends a revised route map bearing the crew’s signatures.',refusal:'“Those seats were a gift. You made them a debt.” Yao honors existing contracts and offers no more personal credit.',rival:'river'}
};
export function arcState(s,id){return s.flags['arc:'+id]||'unopened';}
export function canContact(s,f){return s.chapter===1?s.location===f.place:s.location==='shrine'&&(!!s.flags['talk:'+f.id]||s.build.affiliation===f.id);}
export function bondOptions(s){if(s.combat||s.ending)return [];const out=[];for(const f of factions){const a=personalArcs[f.id],stage=arcState(s,f.id);if(canContact(s,f)){
 if(stage==='unopened'&&s.relationships[f.id]>=1)out.push({id:`bond:${f.id}:open`,label:`${f.npc}: ${a.title}`,detail:'Hear a personal request · 1 turn'});
 if(stage==='ready')out.push({id:`bond:${f.id}:loyal`,label:a.loyal,detail:'1 turn · +2 trust, +1 faction reputation, +2 insight; personal bond'}, {id:`bond:${f.id}:other`,label:a.other,detail:`1 turn · +8 coins; −2 trust, −1 faction reputation; rival reputation +1; private lessons closed`});
 }if(stage==='investigate'&&s.location===a.place)out.push({id:`bond:${f.id}:investigate`,label:a.task,detail:'1 turn · 2 qi · uncover the personal evidence'});
 }return out;}
export function resolveBond(s,id,step){if(!bondOptions(s).some(o=>o.id===`bond:${id}:${step}`))throw Error('That personal request is unavailable here.');const f=factions.find(f=>f.id===id),a=personalArcs[id];let text;
 if(step==='open'){s.flags['arc:'+id]='investigate';text=a.opening;}
 else if(step==='investigate'){if(s.qi<2)throw Error('The investigation needs 2 qi.');s.qi-=2;s.flags['arc:'+id]='ready';text=a.discovery;s.facts.push(`${f.npc}: ${a.discovery}`);}
 else{const loyal=step==='loyal';s.flags['arc:'+id]=loyal?'bonded':'estranged';s.relationships[id]+=loyal?2:-2;s.reputation[id]+=loyal?1:-1;s.flags['mood:'+id]=loyal?'warm':'hostile';if(loyal)s.insight+=2;else{s.coins+=8;s.reputation[a.rival]++;}text=loyal?a.reply:a.refusal;s.memories[id].push('The traveler chose: '+(loyal?a.loyal:a.other)+'. '+text);s.facts.push(a.title+': '+(loyal?a.loyal:a.other));}
 if(step==='open'||step==='investigate'){s.memories[id].push(text);s.memories[id]=s.memories[id].slice(-12);}
 if(step==='investigate')return `${s.chapter>1?'A local dispatch clerk retrieves the valley records. ':''}${text}`;
 return `${f.npc}${s.chapter>1?' writes':''}: ${text}`;
}
export function bondSummary(s){return factions.filter(f=>arcState(s,f.id)!=='unopened').map(f=>{const stage=arcState(s,f.id),a=personalArcs[f.id];return {id:f.id,name:f.npc,title:a.title,stage,next:stage==='investigate'?`${a.task} at ${places[a.place].name}.`:stage==='ready'?s.chapter===1?`Return to ${f.npc} at ${places[f.place].name}.`:'Reply through the shrine letter desk.':stage==='bonded'?'Personal confidence earned.':'Private confidence and lessons withdrawn.'};});}
export function validateBonds(s){for(const f of factions){const stage=arcState(s,f.id);if(!['unopened','investigate','ready','bonded','estranged'].includes(stage))throw Error('Invalid personal arc.');}}
