import {allTechniques} from './personal-art.mjs';
import {sectThreads} from './sect-arcs.mjs';
import {medicineSummary} from './medicine.mjs';
import {provinces,sects,province,sectLocation} from './jianghu.mjs';
import {threshold} from './growth.mjs';
import {factions,techniques,origins} from './world.mjs';
import {buildOptions} from './builds.mjs';
import {bondSummary} from './bonds.mjs';
import {currentRegion,regionSummary} from './regions.mjs';
import {styles} from './combat.mjs';
export function compendium(s,tab,esc,art,stats){
 const guide=[
 ['Field medicine','After chapter one, a clinic teaches field medicine for 3 coins and two turns. Take a shift, examine symptoms, and choose the appropriate care. Examination adds 3 to the higher of Mind or Spirit plus medicine rank; a paid consultation adds another 3. Tonic and splint treatments cost one herb and 2 qi; food and breath care costs 3 qi. Correct, sufficiently skilled care earns the stated fee, medicine experience and Spirit practice. A failed treatment spends resources and requires supervised handover, without a fee. Cases have a cooldown, stay in their original district, and survive saving. Trained healers can buy field remedies; purchases consume local supplies.'],
 ['Growing through experience','Successful work trains Body; investigation and crafting train Mind; practical aid and cultivation train Spirit; new-area exploration and successful stealth train Fate. Victories train Body and the technique attribute used for the finishing blow. Each attribute grows after 8 practice, then 12, 16 and so on, capped at six earned points. Greetings, resting and repeated area searches do not grant growth. Body adds strike damage and 2 maximum health per earned point. Spirit adds 2 maximum qi. All four improve their technique damage and relevant checks. Every two earned Mind add one counter damage; every two earned Fate reduce retreat damage by one, minimum one.'],
 ['Danger and lasting wounds','New opponents gain a threat tier for every five total earned attribute points plus cultivation, capped at four. Each tier adds 4 health and 1 damage to their style; existing fights never rescale. Tier two or higher road challengers are deadly: losing with two existing wounds ends your life permanently. Other defeats leave a wound; each wound reduces outgoing damage by 2. Clinic treatment costs 4 coins and three turns to heal one wound and 8 health. Ordinary rest and herbs restore health but do not heal serious wounds. Second Heart still prevents one lethal blow per chapter.'],
 ['Playing your turn','Type what you do or say in the single text box. Enter sends; Shift+Enter adds a line. You can also choose one of three contextual suggestions or a scene action. Read its cost before choosing. Some actions use two turns. Conversations cost one turn on the first meeting; repeat conversation usually costs none.'],
 ['Narrator and rules','AI interprets intent and describes confirmed events. The rules record, health, qi and inventory determine what happened; prose cannot grant rewards. AI choices are generated but must map to legal actions. Offline choices are authored and clearly labeled. If AI fails, offline actions remain available. Cancel stops generation; it does not undo an action already resolved.'],
 ['Creative attempts','Supported general attempts include investigating, persuading, crafting, sneaking, helping, working, socializing and challenging. They check the relevant attribute + a seeded 1–6 roll + up to 2 cultivation against difficulty 8–11. Crafting costs 2 coins; aid costs 2 qi. Work always pays a small wage. These checks do not simulate arbitrary objectives: a successful persuasion does not found a sect or complete an unrelated quest.'],
 ['Health, qi and recovery','Health measures survival. Herbs restore up to 12 health and take one turn; using one during combat allows the enemy to answer. Rest takes two turns and normally 2 coins, restoring up to 12 health and 8 qi; Jade River restores 10 qi. District scarcity can raise rest to 3 coins. Resources never exceed their maxima. Second Heart can prevent one lethal defeat per chapter. Serious wounds require clinic treatment; scars remain as history.'],
 ['Reading combat','The enemy announces its next intent. Strike uses Body + 2 + cultivation; an enemy guard blocks basic damage. Guard blocks 6 incoming damage and restores 3 qi, or 4 with Still-Water. A matching technique counter adds 2 damage and blocks 5. Iron Vessel blocks one additional damage. Enemy styles have different sequences and guard strength; see Martial arts below. Earned Fate reduces retreat damage. Retreat costs up to 4 health, leaves at least 1 health, and returns you to the gate without victory rewards.'],
 ['Techniques and combinations','Select up to two learned techniques before submitting in combat. Their qi costs add together; Ember Orbit adds one qi and two damage. Technique damage adds each form’s power, one-third of its attribute rounded down, mastery, and cultivation once. Tide-Thread plus Meteor Draw adds 3 damage. Smelted Heaven adds 3 below half health; Verdant Seal restores 4 health. Technique use improves mastery to 3. Training costs 2 qi and two turns, adds one mastery and one insight.'],
 ['Cultivation and blank canvases','A breakthrough needs a practiced technique, 6 qi, two turns and 2 insight. Blank qigong reduces the first insight cost to 1. Each stage adds 2 maximum health and qi; the stage cap rises with chapters to 8. Blank martial arts starts with 3 insight and one free first teacher lesson. Blank qigong starts with extra qi capacity and can learn Still-Water from a trusted valley teacher for 3 coins.'],
 ['People, promises and personal requests','Trust tracks personal confidence; reputation tracks a faction’s opinion. Evidence, work, insults and choices matter. Repeating greetings does not farm trust. Personal requests have an errand and a lasting choice; betrayal can close private teaching even after kind words. Meet contacts in the valley; established contacts exchange letters through shrine desks on later roads. Promises and discovered facts appear in Journal. Some promises are recorded memories rather than fully simulated contracts.'],
 ['The fever chapter','The courier needs an herb before turn 12. Court supplies move at turn 20; the ferry closes at turn 30. The ledger can be taken by combat, a commissioned wedge, or a costly bargain with sufficient Mind. At the tribunal, evidence, allies and prior actions unlock different resolutions. Leaving or losing also concludes the chapter. Continue afterward to keep your character and enter the wider campaign.'],
 ['Districts and ongoing roads','Supplies, safety and prosperity update every 12 turns, even while you are elsewhere. Caravans or spoiled shipments affect stores. Relief preserves supplies but patrol coverage thins; patrols consume stores to improve safety. Safe, supplied districts prosper. Prosperity 60 increases work wages by 1; supplies below 30 raise lodging costs. Market petitions require funding, local work and a report. Each district rewards its petition once; later policy changes cost coin without paying again.'],
 ['Travelers and opportunities','Seeded travelers have names, goals, memories and routes. They move at scheduled times, so an encounter may leave with them or expire. Encounters resolve once; fighting for a road reward never grants the fever ledger. The Travel panel lets you choose among eight regions or follow an unknown road. Crossing regions takes three turns and renews opportunities while retaining character progress, recurring travelers and district conditions. The current world uses a finite set of encounter families.'],
 ['Saving and testing','Every resolved action autosaves in this browser, with a previous-save backup. Settings provides export, import, text transfer and recovery. Older supported saves migrate. If another tab changes the save, reload before playing further or export your tab; stale writes are refused. TEST CHRONICLE uses isolated per-tab session storage and is discarded when its tab closes. Export a test chronicle if you want to keep it.'],
 ['What is still being built','School founding, disciples, aging, succession, advanced professions, complex crafting and full faction wars are not playable yet. Cookie will not pretend a planned system exists. The guide describes current rules; release progress is tracked in the project checklist.']
 ];
 const r=currentRegion(s);
 const journal=`<h3>Your next thread</h3><p>${esc(s.chapter>1?s.quests.road:s.quests.ledger)}</p>${bondSummary(s).map(b=>`<article><h4>${esc(b.title)}</h4><p>${esc(b.name)} · ${esc(b.stage)}<br>${esc(b.next)}</p></article>`).join('')}<h3>Sect requests</h3>${sectThreads(s).map(t=>`<article><h4>${esc(t.title)}</h4><p>${esc(t.stage)} · ${esc(t.next)}</p></article>`).join('')}<h3>Promises</h3><p>${s.promises.map(esc).join('<br>')||'No promises made.'}</p><h3>Discovered facts</h3><p>${s.facts.map(esc).join('<br>')||'No discoveries recorded yet.'}</p><h3>People remember</h3>${factions.filter(f=>s.memories[f.id].length).map(f=>`<article><h4>${esc(f.npc)} · trust ${s.relationships[f.id]}</h4><p>${s.memories[f.id].map(esc).join('<br>')}</p></article>`).join('')}${s.world.people.map(p=>`<article><h4>${esc(p.name)}</h4><p>${esc(p.role)} · ${esc(p.goal)}<br>${p.memories.map(esc).join('<br>')||'No shared memories yet.'}</p></article>`).join('')}${r?`<h3>The living district</h3><p>${esc(regionSummary(s))}</p>${r.history.map(h=>`<p>Turn ${h.time} · ${esc(h.text)}</p>`).join('')}`:''}<h3>Field medicine</h3><p>${esc(medicineSummary(s))}</p>${s.medicine.history.map(h=>`<p>Turn ${h.time} · ${esc(h.text)}</p>`).join('')}<h3>Sect contacts remember</h3>${sects.filter(c=>s.jianghu.memories[c.id].length).map(c=>`<article><h4>${esc(c.npc)}</h4><p>${s.jianghu.memories[c.id].map(esc).join('<br>')}</p></article>`).join('')}<h3>People met on the road</h3>${s.jianghu.people.map(p=>`<article><h4>${esc(p.name)} · ${esc(p.region)}</h4><p>${esc(p.role)} · trust ${p.trust}<br>${p.memories.map(esc).join('<br>')}</p></article>`).join('')}<h3>Past chapters</h3><p>${s.chapters.map(c=>`${esc(c.region)} · ${esc(c.outcome)} · turn ${c.time}`).join('<br>')||'Your first chapter is still unfolding.'}</p>`;
 const banners=`<h3>The wider jianghu</h3>${provinces.map(p=>`<details><summary>${esc(p.name)} · ${esc(p.terrain)}</summary><p>${esc(p.description)} Dominant tradition: ${esc(p.alignment)}.</p></details>`).join('')}<h3>Schools beyond the valley</h3>${sects.map(c=>`<details><summary>${esc(c.name)} · ${esc(c.alignment)} · standing ${s.jianghu.standing[c.id]}</summary><p>${esc(c.npc)}: ${esc(c.goal)}</p><p>Current stop: ${esc(sectLocation(s,c).name)} · ${esc(c.place)}. Their circuit advances every 24 turns. Service earns standing; at standing 2, a 4-coin technique lesson becomes available if you meet its attribute requirement.</p><p>Economy: ${esc(c.economy)}<br>Internal dispute: ${esc(c.dispute)}<br>Relations: ${esc(c.rival)}</p></details>`).join('')}<h3>The eight valley banners</h3>`+factions.map(f=>`<details><summary>${esc(f.name)} · reputation ${s.reputation[f.id]}</summary><h4>${esc(f.npc)}</h4><p>${esc(f.history)}</p><p><b>Territory:</b> ${esc(f.territory)}<br><b>Economy:</b> ${esc(f.economy)}<br><b>Hierarchy:</b> ${esc(f.hierarchy)}<br><b>Rivalry:</b> ${esc(f.rival)}<br><b>Internal dispute:</b> ${esc(f.dispute)}</p></details>`).join('');
 const character=`${art(s,true)}<h3>${esc(s.name)}</h3><p>${esc(origins[s.origin].name)}</p>${stats(s)}<p>Health ${s.hp}/${s.maxHp} · qi ${s.qi}/${s.maxQi}<br>Coins ${s.coins} · herbs ${s.inventory.herb||0}<br>${esc(medicineSummary(s))}<br>Cultivation ${s.cultivation}/${Math.min(8,s.chapter+1)} · insight ${s.insight}<br>Inventory: ${Object.entries(s.inventory).map(([k,v])=>esc(k)+' × '+v).join(', ')}<br>Untreated wounds: ${s.wounds}<br>Growth: ${Object.entries(s.growth).map(([k,g])=>`${k} +${g.level} (${g.level===6?'maximum':g.xp+'/'+threshold(g.level)+' practice'})`).join(', ')}<br>Injuries: ${s.injuries.map(esc).join(', ')||'None'}</p>${Object.entries(s.build).map(([k,v])=>`<p><b>${esc(buildOptions[k].items[v].name)}</b><br>${esc(buildOptions[k].items[v].desc)}</p>`).join('')}<h3>Martial arts</h3><p>Create your own art from Supplies, training &amp; other actions. Choose a foundation; no teacher is required. Evolve it after mastery 3, three combat uses, and cultivation 1/2/3 for successive evolutions. Each evolution resets mastery.</p>${allTechniques(s).map(t=>`<details><summary>${esc(t.name)} ${Object.hasOwn(s.techniques,t.id)?'· '+s.techniques[t.id]+'/3':'· unlearned'}</summary><p>${esc(t.desc)}<br>${t.cost} qi · ${t.stat} · base power ${t.power} · counters ${t.counter}</p>${Object.hasOwn(s.techniques,t.id)?`<button data-action="train:${t.id}" ${s.combat||s.ending||s.techniques[t.id]>=3?'disabled':''}>Train · 2 qi · 2 turns</button>`:'<p>Learn from its trusted faction teacher or an appropriate road lesson. Faction teaching requires the technique attribute to be at least 4.</p>'}</details>`).join('')}<h3>Opponent styles</h3>${Object.values(styles).map(c=>`<details><summary>${esc(c.name)}</summary><p>${esc(c.read)}<br>Heavy ${c.damage.heavy}, quick ${c.damage.quick}, guard ${c.damage.guard}; blocks ${c.block} basic damage.<br>Sequence: ${c.pattern.join(' → ')}</p></details>`).join('')}`;
 return `<details class="panel compendium" id="compendiumPanel"><summary>Cookie’s Compendium</summary><div class="cookie-welcome"><div class="cookie-cat" role="img" aria-label="Cookie, a black cat with an ivory crescent moon on its forehead, blinking gently"></div><p>“Keep your promises. Read the costs. Pet the cat.”<small>Your guide and remembered world.</small></p></div><div class="compendium-tabs" role="tablist" aria-label="Compendium sections">${[['guide','Guide'],['journal','Journal'],['banners','Banners'],['character','Character']].map(([id,label])=>`<button role="tab" id="cookie-tab-${id}" aria-controls="cookie-content" aria-selected="${tab===id}" data-compendium="${id}">${label}</button>`).join('')}</div><section id="cookie-content" role="tabpanel" aria-labelledby="cookie-tab-${tab}">${tab==='guide'?guide.map(([title,text])=>`<details><summary>${title}</summary><p>${text}</p></details>`).join(''):tab==='journal'?journal:tab==='banners'?banners:character}</section></details>`;
}
