import {allTechniques,personalActions,developArt,validatePersonalArt} from './personal-art.mjs';
import {sectArcOptions,resolveSectArc,validateSectArcs,sectThreads} from './sect-arcs.mjs';
import {freshMedicine,medicineOptions,resolveMedicine,validateMedicine,medicineSummary} from './medicine.mjs';
import {freshJianghu,provinces,localPlaces,province,roadContact,arrive,jianghuOptions,jianghuAction,validateJianghu} from './jianghu.mjs';
import {freshGrowth,practice,validateGrowth,scaleEncounter} from './growth.mjs';
import {bondOptions,resolveBond,bondSummary,validateBonds,arcState,canContact} from './bonds.mjs';
import {combatStyle,styles} from './combat.mjs';
import {createRegions,regionalTick,regionalOptions,regionalAction,regionSummary,validateRegions,currentRegion} from './regions.mjs';
import {origins,factions,techniques,places,endings} from './world.mjs';
import {resolveBuild,applyBuild} from './builds.mjs';
import {worldFor,eventChoices,resolveEvent,eventVictory,worldTick} from './procedural.mjs';
import {sandboxOptions,resolveImprovisation,nextRoad,regionName} from './sandbox.mjs';
export const VERSION=5;
const clone=x=>structuredClone(x), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const tech=id=>techniques.find(t=>t.id===id);
export function createCharacter({name='Nameless',origin='oath',gender='male',palette=0,build={},seed=globalThis.crypto?.randomUUID?.()||String(Date.now())}={}) {
 if(!Object.hasOwn(origins,origin)||!['male','female'].includes(gender)||!Number.isInteger(palette)||palette<0||palette>3)throw Error('Invalid character choices.');
 seed=String(seed).slice(0,40); const o=origins[origin];const b=resolveBuild(build),derived=applyBuild(o.stats,b);const relationships=Object.fromEntries(factions.map(f=>[f.id,f.id===b.affiliation?1:0]));const reputation={...relationships};const rivals={jade:'ash',ash:'jade',veil:'masks',masks:'veil',river:'star',star:'river',furnace:'bone',bone:'furnace'};if(rivals[b.affiliation])reputation[rivals[b.affiliation]]=-1;
 return {version:VERSION,growth:freshGrowth(),wounds:0,jianghu:freshJianghu(),medicine:freshMedicine(),chapter:1,chapters:[],seed:String(seed).slice(0,40),world:worldFor(seed),regions:createRegions(seed),name:String(name).trim().slice(0,32)||'Nameless',origin,gender,palette,build:b,stats:derived.stats,hp:derived.hp,maxHp:derived.hp,qi:derived.qi,maxQi:derived.qi,coins:b.affiliation==='wanderer'?16:12,inventory:{herb:2},techniques:b.martial==='none'?{}:{[b.martial]:0},relationships,reputation,memories:Object.fromEntries(factions.map(f=>[f.id,[]])),minor:{id:'courier-lu',name:'Lu Wen',alive:true,memories:[]},promises:[],injuries:[],facts:[],flags:{},quests:{ledger:'Find the fever ledger; decide who should control the medicine.'},time:0,location:'gate',cultivation:0,insight:b.martial==='none'?3:0,combat:null,ending:null,revision:0,journal:[{time:0,kind:'story',text:'Rain finds you before the village does. Your teacher’s last letter said: Find the ledger. Do not trust the seal. The fever courier is dying at the clinic. At the twentieth turn the Court will move the supplies.'}]};
}
function add(s,text,kind='story'){s.journal.push({time:s.time,turn:s.revision+1,kind,text});s.journal=s.journal.slice(-180);}
function fact(s,text){if(!s.facts.includes(text))s.facts.push(text);}
function once(s,key,fn){if(s.flags[key])throw Error('This has already been resolved.');fn();s.flags[key]=true;}
function spend(s,key,n){if(s[key]<n)throw Error(`Not enough ${key}: need ${n}.`);s[key]-=n;}
function finish(s,id){s.ending=id;s.quests.ledger='Chapter complete: '+endings[id][0];add(s,endings[id][1],'ending');if(s.promises.some(p=>p.startsWith('Help the fever families'))&&!s.flags.savedCourier)add(s,'Your promise to save Lu Wen remains broken.','consequence');}
function advance(s,n=1){const before=s.time;s.time+=n;for(const line of [...worldTick(s,before,localPlaces(s)),...regionalTick(s)])add(s,line,'world');
 if((s.chapter||1)===1&&before<12&&s.time>=12&&!s.flags.savedCourier){s.minor.alive=false;fact(s,'Lu Wen died before treatment.');add(s,'A runner brings news: Lu Wen has died. Anwei has written his name. The ledger can still be found.','world');}
 if((s.chapter||1)===1&&before<20&&s.time>=20){s.flags.movedSupplies=true;add(s,'While you were elsewhere, Court porters moved half the medicine. Every resolution will now save fewer people.','world');}
 if((s.chapter||1)===1&&before<30&&s.time>=30){s.flags.ferryClosed=true;add(s,'Qiao takes the waiting families across. The ferry route is closed for tonight.','world');}
}
export function restCost(s){return currentRegion(s)?.supplies<30?3:2;}
export function options(s){if(s.ending)return [];if(s.combat)return [{id:'attack',label:'Strike',detail:'1 turn · body damage; enemy answers'},{id:'guard',label:'Guard & breathe',detail:`1 turn · +${s.build.qigong==='breath'||s.flags.learnedQigong?4:3} qi · reduced damage`},{id:'flee',label:'Break away',detail:`1 turn · ${Math.max(1,4-Math.floor(s.growth.fate.level/2))} damage · lose the attempt`},{id:'heal',label:'Use herb',detail:'1 turn · 1 herb · +12 health'}];
 let a=[...(s.wounds&&s.location==='clinic'?[{id:'recover',label:'Treat a serious wound',detail:'3 turns · 4 coins · heal one wound and 8 health'}]:[]),{id:'explore',label:'Search the area',detail:s.flags['search:'+s.location]?'Already searched':'1 turn · evidence or supplies'},{id:'rest',label:'Rest',detail:`2 turns · ${restCost(s)} coins · +12 health, +${s.build.affinity==='river'?10:8} qi`},{id:'heal',label:'Use herb',detail:'1 turn · 1 herb · +12 health'},{id:'cultivate',label:'Cultivate',detail:`2 turns · 6 qi · needs ${s.build.qigong==='none'&&s.cultivation===0?1:2} insight and practiced technique`}];
 if(s.location==='clinic'&&!s.flags.savedCourier&&s.minor.alive)a.push({id:'save',label:'Treat Lu Wen',detail:'1 turn · 1 herb · save the courier'});
 if(s.location==='market'&&!s.flags.job)a.push({id:'job',label:'Unload Yao’s wagons',detail:'2 turns · earn 8 coins and trust'});
 if(s.location==='forge'&&!s.flags.wedge)a.push({id:'wedge',label:'Commission a sluice wedge',detail:'1 turn · 4 coins'});
 if(s.location==='sluice'&&!s.flags.ledger){a.push({id:'duel',label:'Challenge the enforcer',detail:'Begin combat · defeat yields ledger'});if(s.flags.wedge)a.push({id:'sneak',label:'Open the maintenance lock',detail:'1 turn · wedge · bypass the enforcer'});if(s.stats.mind>=7)a.push({id:'bargain',label:'Buy the enforcer’s silence',detail:'1 turn · 10 coins · acquire ledger'});}
 if(s.flags.ledger&&s.location==='tribunal')a.push(...['justice','mercy','trade','rule'].map(id=>({id:'end:'+id,label:{justice:'Expose the fever conspiracy',mercy:'Entrust medicine to Qiao',trade:'Negotiate a supply contract',rule:'Claim the storehouse'}[id],detail:{justice:'Needs burial evidence and Shen’s trust',mercy:'Needs Qiao’s trust · ferry before turn 30',trade:'Needs Yao’s trust and route manifest',rule:'Needs victory over the enforcer'}[id]})));
 if(['gate','ferry'].includes(s.location))a.push({id:'end:wander',label:'Leave the valley',detail:'Finish chapter · leave the crisis unresolved'});
 if((s.chapter||1)===1&&s.build.qigong==='none'&&!s.flags.learnedQigong&&factions.some(f=>f.place===s.location&&s.relationships[f.id]>=1))a.push({id:'qigong',label:'Learn Still-Water Breathing',detail:'1 turn · 3 coins · Guard restores 4 qi; existing capacity unchanged'});
 if((s.chapter||1)>1){a=a.filter(o=>!['save','job','wedge','duel','sneak','bargain'].includes(o.id)&&!o.id.startsWith('end:'));a.push({id:'road',label:'Take the next road',detail:'3 turns · follow an unknown road; keep your character'});}return [...a,...personalActions(s),...bondOptions(s),...regionalOptions(s),...eventChoices(s),...sandboxOptions(s),...jianghuOptions(s),...medicineOptions(s),...sectArcOptions(s)];
}
export function legalActions(s){return [...options(s).map(x=>x.id),...(!s.combat&&!s.ending?[...(s.chapter>1?provinces.map((p,i)=>'road:'+i):[]),...Object.keys(places).filter(x=>x!==s.location).map(x=>'travel:'+x),...factions.filter(f=>(s.chapter||1)===1&&f.place===s.location).flatMap(f=>['talk:'+f.id,'promise:'+f.id,...(s.relationships[f.id]>=1&&arcState(s,f.id)!=='estranged'?['learn:'+techniques.find(t=>t.faction===f.id).id]:[])]),...Object.keys(s.techniques).map(t=>'train:'+t)]:[]),...(s.combat?Object.keys(s.techniques).map(t=>'tech:'+t):[])];}
export function act(previous,action,{text='',combo=[],tone=''}={}){
 const s=clone(previous);const tech=id=>allTechniques(s).find(t=>t.id===id);if((action==='road'||/^road:[0-7]$/.test(action))&&s.chapter>1&&!s.combat&&!s.ending){advance(s,3);return nextRoad(s,action==='road'?undefined:Number(action.split(':')[1]));}if(s.ending)throw Error('This chapter has ended. Start another chronicle to choose a different path.');
 if(!legalActions(s).includes(action))throw Error('That action is not available here.');
 let [verb,id]=action.split(':');let elapsed=1;const gains=[];const gain=(key,n=1)=>{const line=practice(s,key,n);if(line)gains.push(line);};
 if(s.combat){
 const c=s.combat;let defense=0,damage=0;
 if(verb==='attack')damage=Math.max(1,s.stats.body+2+s.cultivation-s.wounds*2);
 if(verb==='guard'){const gain=s.build.qigong==='breath'||s.flags.learnedQigong?4:3;s.qi=clamp(s.qi+gain,0,s.maxQi);defense=6;if(s.build.unique==='thread'&&!c.threadUsed&&Object.values(s.relationships).some(x=>x>=2)){s.hp=Math.min(s.maxHp,s.hp+3);c.threadUsed=true;add(s,'Red Thread steadies your breath. +3 health.','combat');}add(s,`You give ground, close your guard, and recover ${gain} qi.`,'combat');}
 if(verb==='heal'){if(!s.inventory.herb)throw Error('No herbs remain.');s.inventory.herb--;s.hp=clamp(s.hp+12,0,s.maxHp);add(s,'You crush an herb against your wound. +12 health.','combat');}
 if(verb==='flee'){const retreatCost=Math.max(1,4-Math.floor(s.growth.fate.level/2));s.hp=Math.max(1,s.hp-retreatCost);s.combat=null;s.location='gate';add(s,(c.event||c.sandbox?'You break away from the road opponent. No victory reward is claimed.':'You escape through the runoff. The enforcer keeps the ledger.')+` −${retreatCost} health.`,'combat');}
 if(verb==='tech'){
 const ids=[...new Set([id,...combo])];if(ids.length>2||ids.some(x=>!Object.hasOwn(s.techniques,x)))throw Error('Combine at most two learned techniques.');
 const ts=ids.map(tech);spend(s,'qi',ts.reduce((v,t)=>v+t.cost,0)+(s.build.qigong==='ember'?1:0));
 damage=ts.reduce((v,t)=>v+t.power+Math.floor(s.stats[t.stat]/3)+s.techniques[t.id],0)+s.cultivation;
 damage=Math.max(1,damage-s.wounds*2);if(ts.some(t=>t.counter===c.intent)){defense=5;damage+=2+Math.floor(s.growth.mind.level/2);}else if(s.build.unique==='fate'&&!c.fateUsed){defense=4;damage+=4;c.fateUsed=true;add(s,'Borrowed Fate bends one opening your way. +4 damage, 4 protection.','combat');}
 damage+=(s.build.affinity==='cinder'?1:0)+(s.build.qigong==='ember'?2:0);
 if(ids.includes('tide')&&ids.includes('meteor'))damage+=3;
 if(ids.includes('smelt')&&s.hp<s.maxHp/2)damage+=3;
 if(ids.includes('seal'))s.hp=clamp(s.hp+4,0,s.maxHp);
 if(ids.includes('personal'))s.personalArt.uses=Math.min(3,s.personalArt.uses+1);
 for(const t of ts)s.techniques[t.id]=Math.min(3,s.techniques[t.id]+1);
 add(s,ts.map(t=>t.name).join(' + ')+` deals ${damage} damage${defense?' and counters the incoming strike':''}.`,'combat');
 }
 if(s.combat){if(c.intent==='guard'&&verb==='attack')damage=Math.max(1,damage-combatStyle(c).block);c.hp-=damage;if(verb==='attack')add(s,`Your strike deals ${damage} damage.`,'combat');
 if(c.hp<=0){gain('body',2);if(verb==='tech')gain(tech(id).stat);s.combat=null;if(c.sandbox){s.insight+=2;s.coins+=6;add(s,'The road opponent yields. +2 insight, +6 coins. Your journey continues.','combat');}else if(c.event){add(s,eventVictory(s,c),'combat');}else{s.flags.victory=true;s.flags.ledger=true;s.inventory.ledger=1;s.insight+=2;s.reputation.ash+=2;fact(s,'The enforcer was defeated; the stolen ledger is yours.');add(s,'The enforcer drops his warrant. In the medicine chest: your teacher’s ledger, intact. You can take it to the tribunal.','combat');}}
 else {const hit=Math.max(0,combatStyle(c).damage[c.intent]-defense-(s.build.qigong==='iron'?1:0));s.hp=clamp(s.hp-hit,0,s.maxHp);add(s,`${c.name||'The enforcer'}’s ${c.intent} action costs you ${hit} health.`,'combat');c.turn++;c.intent=combatStyle(c).pattern[c.turn%combatStyle(c).pattern.length];if(s.hp===0){if(s.build.unique==='heart'&&!s.flags.secondHeart){s.flags.secondHeart=true;s.hp=8;s.injuries.push('Second Heart scar');add(s,'Your Second Heart catches. You stand at 8 health. It will not happen twice.','combat');}else{const fatal=!!c.lethal&&s.wounds>=2;s.wounds=Math.min(3,s.wounds+1);s.injuries.push((c.event||c.sandbox)?'Road encounter scar':'Sluice scar');add(s,'A serious wound remains: each untreated wound reduces outgoing damage by 2. Treatment at a clinic is needed.','consequence');s.hp=1;s.combat=null;if(fatal){s.hp=0;finish(s,'death');}else if(c.event||c.sandbox){s.coins=Math.max(0,s.coins-3);s.location='gate';add(s,'You wake near '+localPlaces(s).gate.name+', three coins lighter. The encounter is lost, but your chapter continues.','combat');}else finish(s,'defeat');}}}}
 }else if(verb==='invent'||verb==='evolve'){add(s,developArt(s,verb,id,text));elapsed=3;}else if(verb==='sectarc'){const step=action.split(':')[2];add(s,resolveSectArc(s,id,step),step==='open'?'dialogue':'story');if(step==='proof')gain('mind');if(step==='loyal')gain('spirit');}
 else if(verb==='medicine'){const result=resolveMedicine(s,id);elapsed=result.time;add(s,result.text,'story');if(result.practice)gain(result.practice);}
 else if(verb==='sect'||verb==='meeting'){const result=jianghuAction(s,verb,id,text,tone);elapsed=result.time;add(s,result.text,id==='talk'||id==='listen'?'dialogue':'story');if(id==='help'||id==='serve')gain('spirit');}
 else if(verb==='bond'){add(s,resolveBond(s,id,action.split(':')[2]),'dialogue');}
 else if(verb==='region'){const result=regionalAction(s,id);elapsed=result.time;add(s,result.text,'world');}
 else if(verb==='improvise'){const result=resolveImprovisation(s,id,text);elapsed=result.time;if(result.practice)gain(result.practice);add(s,result.text,'story');}
 else if(verb==='event'){const event=resolveEvent(s,id);elapsed=event.time;add(s,event.text,'world');}
 else if(verb==='travel'){s.location=id;delete s.flags.speaker;add(s,(s.chapter||1)>1?'You reach '+localPlaces(s)[id].name+' in '+regionName(s)+'. '+province(s).description:places[id].text);const meeting=arrive(s);if(meeting)add(s,meeting,'world');}
 else if(verb==='explore'&&(s.chapter||1)>1){once(s,'search:'+s.location,()=>{const result=resolveImprovisation(s,'observe','Search '+localPlaces(s)[s.location].name+' in '+regionName(s));add(s,result.text);});}
 else if(verb==='explore'){once(s,'search:'+s.location,()=>{
 const rewards={gate:()=>{s.inventory.herb++;add(s,'In an abandoned guard pouch: one sealed medicinal herb.');},clinic:()=>{s.flags.route=true;fact(s,'The convoy manifest identifies a Court shipment at the sluice.');add(s,'The courier hid a convoy manifest beneath the cot. The destination reads EAST SLUICE.');},market:()=>{s.coins+=4;add(s,'You return a dropped purse. The tea seller insists you keep four coins.');},ferry:()=>{s.relationships.river++;add(s,'You retie a drifting skiff. Qiao notices your hands, not your words.');},forge:()=>{s.insight++;add(s,'A broken lock reveals how force travels through metal. +1 insight.');},shrine:()=>{s.flags.burial=true;s.insight++;fact(s,'The burial register proves the Court concealed fever deaths.');add(s,'Anwei lets you copy the burial register. The official count is a lie. +1 insight.');},sluice:()=>{s.insight++;add(s,'You study the enforcer: a heavy blow, a quick cut, then a guarded pause. +1 insight.');},tribunal:()=>{add(s,'The table has room for a ledger, a burial register, and witnesses. Justice will need all three.');}};rewards[s.location]();if(s.build.affinity==='void'){s.insight++;add(s,'Void Listening reveals a pattern. +1 insight.');}});}
 else if(verb==='talk'||verb==='promise'){
 const f=factions.find(f=>f.id===id);const m=s.memories[id];
 if(verb==='promise'){once(s,'promise:'+id,()=>{s.promises.push('Help the fever families, witnessed by '+f.npc);m.push('The traveler promised to help the fever families.');add(s,`${f.npc}: “I heard your promise. I will remember it.”`,'dialogue');});}
 else {const first=!s.flags['talk:'+id];if(first){s.flags['talk:'+id]=true;s.relationships[id]++;s.reputation[id]++;m.push('Met at '+places[s.location].name);}
 let reaction='';if(text){m.push('Heard the traveler say: '+text.slice(0,250));m.splice(0,Math.max(0,m.length-12));const lower=text.toLowerCase();
 const hostile=tone==='hostile'||/\b(kill|threaten|idiot|coward|worthless|shut up|hurt you)\b/.test(lower)&&!/\b(won.t|will not|never|don.t)\b/.test(lower);
 const evidence=/\b(ledger|evidence|register|manifest)\b/.test(lower)&&(s.flags.ledger||s.flags.burial||s.flags.route);
 const kind=tone==='kind'||/\b(thank|sorry|help|trust|protect|understand|safe)\b/.test(lower);
 if(hostile){s.flags['mood:'+id]='hostile';if(!s.flags['insult:'+id]){s.relationships[id]--;s.reputation[id]--;s.flags['insult:'+id]=true;}reaction={jade:'Threats are not testimony. Lower your voice.',ash:'Say it again when you can afford the answer.',veil:'That is anger speaking. It knows less than you think.',river:'Even a boat has limits to what it will carry.',furnace:'Do not mistake a hammer for patience.',masks:'How disappointing. I thought you had a better part to play.',bone:'I will treat your wounds. I will not excuse your cruelty.',star:'That is the end of the friendly price.'}[id];}
 else if(evidence){s.flags['mood:'+id]='warm';if(!s.flags['evidence:'+id]){s.relationships[id]++;s.flags['evidence:'+id]=true;m.push('Saw evidence of the medicine conspiracy.');}reaction='I can speak for what you have shown me. I will remember this evidence.';}
 else if(kind){s.flags['mood:'+id]='warm';reaction=s.flags['insult:'+id]?'I heard the kind words. Trust will take deeds, not another sentence.':({jade:'Then begin with the person in front of you. There is work enough here.',ash:'Help is a heavy word. Carry it carefully.',veil:'I hear you. Let us see what follows.',river:'There is always another rope to tie. Sit with me a moment.',furnace:'Good. Hold the light steady.',masks:'A generous opening. I hope the next act deserves it.',bone:'Thank you. Kindness is still a choice here.',star:'Then we may yet find a road we can share.'}[id]);}
 else{s.flags['mood:'+id]=s.relationships[id]>=2?'warm':'neutral';reaction=f.knowledge;}
 }
 if(arcState(s,id)==='estranged')s.flags['mood:'+id]='hostile';const line=arcState(s,id)==='estranged'?'I will speak about public business. My private confidence is closed.':reaction|| (s.relationships[id]>=2?f.trust:first?f.line:'“'+f.knowledge+'”');add(s,`${f.npc}: ${line}`,'dialogue');if(!first)elapsed=0;}
 s.flags.speaker=id;
 }
 else if(verb==='learn'){const t=tech(id);if(Object.hasOwn(s.techniques,id))throw Error('You already know this technique. Train it instead.');if(s.stats[t.stat]<4)throw Error('Requires '+t.stat+' 4.');if(s.build.martial==='none'&&!s.flags.blankLearned){s.flags.blankLearned=true;}else spend(s,'coins',3);s.techniques[id]=0;s.memories[t.faction].push('Taught '+t.name);add(s,'You learn the first form of '+t.name+'. Mastery requires practice.');}
 else if(verb==='recover'){spend(s,'coins',4);s.wounds--;elapsed=3;s.hp=Math.min(s.maxHp,s.hp+8);add(s,'A physician sets the injury and supervises three turns of recovery. One wound heals; +8 health. Scars remain in your history.');}
 else if(verb==='train'){if(s.techniques[id]>=3)throw Error('Chapter mastery cap reached.');spend(s,'qi',2);s.techniques[id]++;s.insight++;gain(tech(id).stat);elapsed=2;add(s,`Two turns of practice: ${tech(id).name} mastery ${s.techniques[id]}/3. +1 insight.`);}
 else if(verb==='qigong'){spend(s,'coins',3);s.flags.learnedQigong=true;add(s,'A teacher shows you Still-Water Breathing. Your Guard now restores 4 qi.');}
 else if(verb==='cultivate'){if(s.cultivation>=Math.min(8,(s.chapter||1)+1))throw Error('You have reached this chapter’s cultivation limit.');const needed=s.build.qigong==='none'&&s.cultivation===0?1:2;if(s.insight<needed||!Object.values(s.techniques).some(v=>v>=1))throw Error(`Needs ${needed} insight and at least one practiced technique.`);spend(s,'qi',6);s.insight-=needed;s.cultivation++;gain('spirit',2);s.maxQi+=2;s.maxHp+=2;s.hp=Math.min(s.maxHp,s.hp+2);elapsed=2;fact(s,'Earned cultivation stage '+s.cultivation);add(s,'The meridian opens by a hair’s breadth. No thunder. Just a breath that no longer hurts. +2 maximum health and qi.');}
 else if(verb==='rest'){spend(s,'coins',restCost(s));s.hp=clamp(s.hp+12,0,s.maxHp);s.qi=clamp(s.qi+8+(s.build.affinity==='river'?2:0),0,s.maxQi);elapsed=2;add(s,'You pay for a dry mat and a bowl of broth. +12 health; qi restored (8, or 10 with Jade River). The town keeps moving.');}
 else if(verb==='heal'){if(!s.inventory.herb)throw Error('No herbs remain.');if(s.hp===s.maxHp)throw Error('You are already at full health.');s.inventory.herb--;s.hp=clamp(s.hp+12,0,s.maxHp);add(s,'A bitter herb closes the worst of the wound. +12 health.');}
 else if(verb==='save'){once(s,'savedCourier',()=>{if(!s.inventory.herb)throw Error('You need an herb.');s.inventory.herb--;s.relationships.jade+=2;s.relationships.bone++;if(s.build.unique==='thread'){s.relationships.jade++;s.relationships.bone++;}s.insight++;s.minor.memories.push('The traveler saved my life.');fact(s,'Lu Wen was saved and named the sluice as the ledger’s hiding place.');add(s,'Lu Wen swallows the medicine. “Your teacher hid it in the sluice. She stayed behind so I could run.” Shen puts a clean cloth over his hand. +1 insight.');});}
 else if(verb==='job'){once(s,'job',()=>{s.coins+=8;s.relationships.star+=2;elapsed=2;add(s,'You unload medicine until your hands shake. Yao pays eight coins and remembers who did the work.');});}
 else if(verb==='wedge'){once(s,'wedge',()=>{spend(s,'coins',4);s.inventory.wedge=1;s.relationships.furnace++;add(s,'Du tempers a wedge for the sluice lock. “Use this to open something.”');});}
 else if(verb==='duel'){s.combat={hp:38,maxHp:38,name:'Court enforcer',turn:0,intent:'heavy'};add(s,'The enforcer lays down his brazier. His shoulder rises: a heavy blow is coming.','combat');}
 else if(verb==='sneak'||verb==='bargain'){if(verb==='bargain')spend(s,'coins',10);else{delete s.inventory.wedge;s.flags.wedge=false;}s.flags.ledger=true;s.inventory.ledger=1;s.insight++;fact(s,'The stolen ledger is yours; the enforcer lives.');add(s,'You take the ledger from the medicine chest. Your teacher has signed every page. Bring it to the tribunal, or leave with it.');}
 else if(verb==='end'){
 if(id==='justice'&&(!s.flags.burial||s.relationships.jade<2))throw Error('Justice needs the burial register and Shen’s trust (2).');
 if(id==='mercy'&&(s.relationships.river<1||s.flags.ferryClosed))throw Error('You need Qiao’s trust and an open ferry before turn 30.');
 if(id==='trade'&&(!s.flags.route||s.relationships.star<2))throw Error('Trade needs the convoy manifest and Yao’s trust (2).');
 if(id==='rule'&&!s.flags.victory)throw Error('You must defeat the enforcer before claiming the storehouse.');
 if(id==='trade')s.coins+=20;if(id==='rule'){s.reputation.jade-=3;s.reputation.ash+=3;}
 finish(s,id);if(s.flags.movedSupplies&&id!=='wander')add(s,'Because the Court moved first, only half the original medicine remains.','consequence');
 if(s.flags.savedCourier)add(s,'Lu Wen lives to tell the story. He remembers the hand that held the cup.','consequence');
 }
 if(verb==='explore')gain('fate');if(verb==='save')gain('spirit',2);if(verb==='job')gain('body',2);if(!previous.combat&&s.combat){scaleEncounter(s);add(s,`Opponent: ${s.combat.maxHp} health, threat tier ${s.combat.threat}. Untreated wounds: ${s.wounds}. ${s.combat.lethal?'Deadly opponent: defeat with two existing wounds means death.':'Defeat leaves a serious wound.'} Retreat before exhaustion.`, 'combat');}for(const line of gains)add(s,line,'progress');if(elapsed&&!s.ending)advance(s,elapsed);s.inventory.herb=Math.min(100,s.inventory.herb||0);for(const key of ['facts','promises','injuries'])s[key]=s[key].slice(-180).map(x=>x.slice(0,1000));s.revision++;return s;
}
export function interpret(s,raw,mode='action'){
 const text=String(raw).trim().slice(0,1000);if(!text)return {clarify:'Describe one action.'};
 if(mode==='action'&&/^(?:["“]|(?:i\s+)?(?:say|ask|tell|reply|speak)\b)/i.test(text))return interpret(s,text,'speech');
 if(mode==='speech'){if((s.chapter||1)>1)return {action:roadContact(s)?'sect:talk':s.jianghu.active?'meeting:listen':'improvise:social',text};const npc=factions.find(f=>f.id===s.flags.speaker&&f.place===s.location)||factions.find(f=>f.place===s.location);return npc?{action:'talk:'+npc.id,text}:{clarify:'There is no conversation partner here. Travel to a populated location.'};}
 const l=text.toLowerCase();const found=allTechniques(s).filter(t=>l.includes(t.name.toLowerCase()));
 if(found.length){if(!s.combat)return {clarify:'Technique use is supported in combat; outside combat, select training or a concrete scene action.'};if(found.some(t=>!Object.hasOwn(s.techniques,t.id)))return {clarify:'You have not learned all of those techniques.'};return {action:'tech:'+found[0].id,combo:found.slice(1).map(t=>t.id)};}
 const candidates=[];for(const o of options(s)){if(l===o.label.toLowerCase()||l===o.id)candidates.push(o.id);}
 const matches=[[/\b(attack|strike|hit)\b/,'attack'],[/\b(guard|defend)\b/,'guard'],[/\b(flee|retreat)\b/,'flee'],[/\b(search|explore|investigate)\b/,'explore'],[/\b(rest|sleep)\b/,'rest'],[/\b(cultivate|meditate)\b/,'cultivate'],[/\b(treat|save)\b.*\b(lu|courier)\b/,'save'],[/\b(heal|herb)\b/,'heal']];for(const [re,id]of matches)if(re.test(l)&&legalActions(s).includes(id))candidates.push(id);
 for(const [id,p]of Object.entries(localPlaces(s)))if(l.includes(p.name.toLowerCase())&&/\b(go|travel|visit|walk)\b/.test(l))candidates.push('travel:'+id);
 if(!candidates.length&&!s.combat){const approaches=[[/\b(repair|craft|forge|sew|stitch|make a|prepare a remedy)\b/,'craft'],[/\b(persuade|negotiate|convince|bargain|reason with)\b/,'persuade'],[/\b(sneak|steal|pickpocket|hide|slip past)\b/,'sneak'],[/\b(help|aid|protect|carry the injured)\b/,'aid'],[/\b(work|earn|trade|haul|unload)\b/,'labor'],[/\b(challenge|duel|fight)\b/,'challenge'],[/\b(observe|inspect|study the|read the|examine|listen|look around)\b/,'observe']];for(const [pattern,approach] of approaches)if(pattern.test(l)&&legalActions(s).includes('improvise:'+approach))candidates.push('improvise:'+approach);}
 if(s.chapter>1&&/\b(go|travel|visit|walk)\b/.test(l))provinces.forEach((p,i)=>{if(l.includes(p.name.toLowerCase()))candidates.push('road:'+i);});if(/\b(treat|recover)\b.*\b(wound|injur)/.test(l)&&legalActions(s).includes('recover'))candidates.push('recover');const unique=[...new Set(candidates)];return unique.length===1?{action:unique[0],text}: {clarify:unique.length>1?'That describes several actions. Choose the first action to resolve.':'I could not identify the main intent. Are you investigating, negotiating, helping, crafting, working, sneaking, or challenging someone? Describe the target and your immediate attempt.'};
}
export function context(s){return {character:{name:s.name,stats:s.stats,growth:s.growth,wounds:s.wounds,hp:s.hp,qi:s.qi,injuries:s.injuries,techniques:s.techniques,personalArt:s.personalArt,techniqueDetails:allTechniques(s).filter(t=>Object.hasOwn(s.techniques,t.id))},location:localPlaces(s)[s.location],travelDestinations:s.chapter>1?provinces.map((p,i)=>({action:'road:'+i,name:p.name,terrain:p.terrain})):[],localDestinations:Object.entries(localPlaces(s)).map(([id,p])=>({action:'travel:'+id,name:p.name})),jianghu:province(s),fieldMedicine:medicineSummary(s),roadMeeting:s.jianghu.people.find(p=>p.id===s.jianghu.active)||null,region:regionName(s),regionalConditions:regionSummary(s),personalThreads:[...bondSummary(s),...sectThreads(s)],chapter:s.chapter,priorChapters:s.chapters.slice(-4),time:s.time,facts:s.facts,promises:s.promises,quests:s.quests,minor:s.minor,procedural:s.world.people.map(p=>({name:p.name,goal:p.goal,memories:p.memories,trust:p.trust})),combat:s.combat,npcs:factions.filter(f=>(s.chapter||1)===1&&f.place===s.location).map(f=>({name:f.npc,voice:f.voice,knowledge:f.knowledge,goal:f.goal,relationship:s.relationships[f.id],memories:s.memories[f.id]})).concat(roadContact(s)?[{name:roadContact(s).npc,voice:roadContact(s).voice,knowledge:roadContact(s).line,goal:roadContact(s).goal,relationship:s.jianghu.standing[roadContact(s).id],memories:s.jianghu.memories[roadContact(s).id]}]:[]),recent:s.journal.filter(e=>e.kind!=='ai').slice(-8),legalActions:legalActions(s)};}
export function validateSave(s){
 s=clone(s);if(s){s.chapter??=1;s.chapters??=[];}
 if(!s||s.version!==VERSION||!Object.hasOwn(origins,s.origin)||!Object.hasOwn(places,s.location)||!['male','female'].includes(s.gender)||!Number.isInteger(s.palette)||s.palette<0||s.palette>3)throw Error('Unsupported or invalid save.');
 if(s.regionIndex!==undefined&&(!Number.isInteger(s.regionIndex)||s.regionIndex<0||s.regionIndex>7))throw Error('Invalid province.');validatePersonalArt(s);validateSectArcs(s);validateMedicine(s);validateJianghu(s);validateGrowth(s);validateRegions(s);validateBonds(s);const base=createCharacter(s);for(const k of ['hp','maxHp','qi','maxQi','coins','time','insight','cultivation','revision'])if(!Number.isInteger(s[k])||s[k]<0||s[k]>1000000000)throw Error('Invalid save field: '+k);
 if((s.hp===0)!==(s.ending==='death'))throw Error('Invalid life state.');
 if(s.hp>s.maxHp||s.qi>s.maxQi||s.cultivation>8||s.maxHp!==base.maxHp+s.cultivation*2+s.growth.body.level*2||s.maxQi!==base.maxQi+s.cultivation*2+s.growth.spirit.level*2)throw Error('Invalid character limits.');
 for(const k of Object.keys(base.stats))if(s.stats?.[k]!==base.stats[k]+s.growth[k].level)throw Error('Invalid derived stats.');
 for(const k of ['facts','promises','injuries','journal'])if(!Array.isArray(s[k])||s[k].length>200)throw Error('Invalid history.');
 for(const k of ['facts','promises','injuries'])if(s[k].some(x=>typeof x!=='string'||x.length>1000))throw Error('Invalid memory.');
 if(s.journal.some(x=>typeof x.text!=='string'||x.text.length>4000||!Number.isInteger(x.time)||typeof x.kind!=='string'))throw Error('Invalid journal.');
 for(const f of factions){if(!Number.isInteger(s.relationships?.[f.id])||!Number.isInteger(s.reputation?.[f.id])||!Array.isArray(s.memories?.[f.id])||s.memories[f.id].some(x=>typeof x!=='string'||x.length>1000))throw Error('Invalid NPC memory.');}
 if(!s.flags||typeof s.flags!=='object'||Array.isArray(s.flags)||Object.keys(s.flags).some(k=>k==='__proto__'||!['boolean','string'].includes(typeof s.flags[k])))throw Error('Invalid flags.');
 if(!s.inventory||Object.entries(s.inventory).some(([k,v])=>!['herb','ledger','wedge'].includes(k)||!Number.isInteger(v)||v<0||v>100))throw Error('Invalid inventory.');
 if(!s.techniques||Object.entries(s.techniques).some(([k,v])=>!allTechniques(s).find(t=>t.id===k)||!Number.isInteger(v)||v<0||v>3))throw Error('Invalid techniques.');
 if(s.ending&&!Object.hasOwn(endings,s.ending))throw Error('Invalid ending.');
 if(s.combat?.lethal!==undefined&&typeof s.combat.lethal!=='boolean')throw Error('Invalid combat danger.');
 if(s.combat?.threat!==undefined&&(!Number.isInteger(s.combat.threat)||s.combat.threat<0||s.combat.threat>4))throw Error('Invalid threat.');
 if(s.combat?.style&&!Object.hasOwn(styles,s.combat.style))throw Error('Invalid combat style.');
 if(s.combat&&(!['heavy','quick','guard'].includes(s.combat.intent)||!Number.isInteger(s.combat.hp)||s.combat.hp<1||s.combat.hp>s.combat.maxHp||!Number.isInteger(s.combat.maxHp)||s.combat.maxHp<20||s.combat.maxHp>80||!Number.isInteger(s.combat.turn)||s.combat.turn<0))throw Error('Invalid combat.');
 if(typeof s.name!=='string'||s.name.length>32||s.minor?.id!=='courier-lu'||typeof s.minor.alive!=='boolean'||!Array.isArray(s.minor.memories)||!s.quests||typeof s.quests.ledger!=='string')throw Error('Invalid character history.');if(typeof s.seed!=='string'||s.seed.length>40||!s.world||s.world.seed!==(s.chapter===1?s.seed:s.seed+':road:'+s.chapter)||!Array.isArray(s.world.people)||s.world.people.length!==4||!s.world.events)throw Error('Invalid procedural world.');if(!Number.isInteger(s.chapter)||s.chapter<1||!Array.isArray(s.chapters))throw Error('Invalid journey.');const generated=worldFor(s.world.seed);for(let i=0;i<4;i++){const p=s.world.people[i],expected=generated.people[i];for(const key of ['id','name','role','temperament','home','destination','moveAt','goal'])if(p[key]!==expected[key])throw Error('Invalid procedural identity.');if(!Number.isInteger(p.trust)||!Array.isArray(p.memories)||p.memories.length>30||p.memories.some(m=>typeof m!=='string'||m.length>1000))throw Error('Invalid procedural memory.');}for(const [k,e]of Object.entries(generated.events)){const actual=s.world.events[k];if(!actual||actual.template!==e.template||actual.npc!==e.npc||actual.technique!==e.technique||actual.expires!==e.expires||typeof actual.resolved!=='boolean')throw Error('Invalid procedural event.');}return clone(s);
}
function checksum(str){let h=2166136261;for(let i=0;i<str.length;i++)h=Math.imul(h^str.charCodeAt(i),16777619);return (h>>>0).toString(16);}
export function encode(s){validateSave(s);const payload=JSON.stringify(s);return JSON.stringify({format:'vermilion-path',version:VERSION,checksum:checksum(payload),payload});}
export function decode(raw){if(typeof raw!=='string'||raw.length>1000000)throw Error('Save is too large.');const e=JSON.parse(raw);if(e.format!=='vermilion-path'||![2,3,4,VERSION].includes(e.version)||typeof e.payload!=='string'||e.checksum!==checksum(e.payload))throw Error('Save checksum or version is invalid.');const s=JSON.parse(e.payload);if(e.version===2&&s.version===2){s.version=3;s.seed=('legacy-'+s.name).slice(0,40);s.world=worldFor(s.seed);}if(s.version===3){s.version=4;s.regions=createRegions(s.seed,s.time);}if(s.version===4){s.version=VERSION;s.growth=freshGrowth();s.wounds=0;}s.jianghu??=freshJianghu();s.jianghu.memories??=freshJianghu().memories;s.medicine??=freshMedicine();return validateSave(s);}
export function save(storage,s){const data=encode(s);const prior=storage.getItem('vp.save');if(prior){try{decode(prior);storage.setItem('vp.backup',prior);}catch{}}storage.setItem('vp.save',data);}
export function load(storage){const a=storage.getItem('vp.save'),b=storage.getItem('vp.backup');for(const [raw,recovered]of [[a,false],[b,true]])if(raw){try{return {state:decode(raw),recovered};}catch{}}return {state:null,corrupt:!!(a||b)};}
