import {hashSeed} from './procedural.mjs';
import {places,techniques} from './world.mjs';
export const provinces=[
 ['Black Reed','Southern marshes','Reed beds conceal toll boats and flooded ancestral halls. Salt, fish and hidden ferries sustain the villages.','unorthodox',['Reed Causeway','Stilt Infirmary','Salt Exchange','Ghostwater Landing','Bog-Iron Kiln','Drowned Ancestor Hall','Smuggler Canal','Boatmasters Court']],
 ['Fallen Plum','Western highlands','Terraced tea farms cling beneath sword monasteries. Winter avalanches can close the only grain road.','orthodox',['Avalanche Pass','Tea-House Hospice','Plum Terrace Bazaar','Cloudchain Crossing','Monastery Smithy','White Crane Hermitage','Snowmelt Dam','Elders Pavilion']],
 ['Cinder Ford','Volcanic frontier','Obsidian ridges surround furnace towns. Foundry masters and exiled cultivators compete for sulfur and clean water.','demonic',['Obsidian Road','Ashlung Hospice','Charcoal Market','Boiling River Ford','Nine-Bell Foundry','Ember Sanctuary','Basalt Waterworks','Founders Hall']],
 ['White Heron','Eastern riverlands','Rice barges pass examination towns and silk estates. Public law protects trade; private debts own the docks.','orthodox',['Heron Tollhouse','Silkward Clinic','Rice-Barge Exchange','Hundred Sails Quay','Canal Armory','Scholar Shrine','Imperial Lock','River Magistracy']],
 ['Broken Moon','Northern steppe','Horse clans follow the grass beyond ruined border walls. Cultivators shelter forbidden manuscripts in saddle shrines.','demonic',['Fallen Wall','Felt-Tent Healer','Horse Fair','Frozen Ford','Steppe Forge','Moon Cairn','Glacier Channel','Khan Council']],
 ['Nine Wells','Desert caravan road','Water shares pass from parent to child. Caravan leagues broker fragile peace between oasis guards and dune raiders.','unorthodox',['Sandstone Gate','Wellside Healer','Saffron Exchange','Dry-River Crossing','Glassfire Workshop','Nine Springs Shrine','Hidden Cistern','Water Tribunal']],
 ['Quiet Thunder','Central mountain forests','Medicinal groves surround secluded academies. Rival teachers dispute whether dangerous forms should be sealed or shared.','orthodox',['Cedar Stair','Root-and-Bark Clinic','Rainleaf Market','Hanging Bridge','Thunderstone Forge','Listening Monastery','Gorge Spillway','Academy Hall']],
 ['Red Willow','Coastal archipelago','Typhoon harbors shelter pearl divers, smugglers and sea temples. Island captains answer to contracts before banners.','unorthodox',['Stormbreak Gate','Divers Hospice','Pearl Market','Red Sail Harbor','Anchor Forge','Sea Mother Shrine','Tidal Grotto','Captains Assembly']]
].map(([name,terrain,description,alignment,names])=>({name,terrain,description,alignment,names}));
export const sects=[
 {id:'crane',lesson:'seal',route:[1,3,6],name:'White Crane Covenant',alignment:'orthodox',npc:'Yun Soyeon',place:'shrine',art:'yun.png',voice:'Clipped, judicial; asks who bears the cost.',goal:'Protect villages without turning her disciples into tax collectors.',dispute:'Her elders demand loyalty to corrupt magistrates.',economy:'Tea terraces and escorted grain caravans.',rival:'Opposes Cinder Vow coercive initiation; secretly buys Reed Compact passage.',line:'A righteous banner is a claim. Show me whose roof it repaired.'},
 {id:'reed',lesson:'tide',route:[5,0,7],name:'Reed Compact',alignment:'unorthodox',npc:'Ma Jun, the Laughing Ferryman',place:'ferry',art:'ma-jun.png',voice:'Warm trade metaphors; never gives a promise without terms.',goal:'Keep waterways open to people outlawed by the great schools.',dispute:'Smugglers want to trade captives; boat families threaten secession.',economy:'Ferries, salvage and discreet courier routes.',rival:'Undercuts Crane tolls; owes the Cinder healers an unpaid rescue debt.',line:'Orthodox silver sinks as quickly as stolen silver. Tell me who needs the boat.'},
 {id:'cinder',lesson:'smelt',route:[2,4],name:'Cinder Vow',alignment:'demonic',npc:'Seol Hwa, Keeper of Embers',place:'forge',art:'seol.png',voice:'Quiet, precise; speaks of pain without glorifying it.',goal:'End forced initiation while preserving the exiles her order shelters.',dispute:'The inner furnace circle demands blood oaths and obedience.',economy:'Obsidian tools, geothermal baths and forbidden meridian treatment.',rival:'Hunted by Crane elders; trades medicine for Reed escape routes.',line:'They call our breath demonic. Some of our elders have worked hard to deserve it. I have not sworn to excuse them.'}
];
export const freshJianghu=()=>({people:[],active:null,serial:0,memories:{crane:[],reed:[],cinder:[]},standing:{crane:0,reed:0,cinder:0}});
export const province=s=>s.chapter>1?provinces[s.regionIndex??hashSeed(s.seed+':'+s.chapter)%8]:null;
export function localPlaces(s){const p=province(s);return p?Object.fromEntries(Object.keys(places).map((key,i)=>[key,{name:p.names[i],text:p.description}])):places;}
export const sectLocation=(s,c)=>provinces[c.route[Math.floor(s.time/24)%c.route.length]];
export function roadContact(s){const p=province(s);return p?sects.find(x=>sectLocation(s,x).name===p.name&&x.place===s.location):null;}
const roles={gate:['pilgrim','deliver a letter before the mountain road closes'],clinic:['herb gatherer','bring fever herbs to an isolated household'],market:['caravan cook','replace supplies spoiled by the weather'],ferry:['boat repairer','get a stranded family across the water'],forge:['runaway apprentice','buy passage without returning to an abusive master'],shrine:['wandering scholar','identify the owner of an unmarked grave'],sluice:['canal worker','repair a dangerous breach before nightfall'],tribunal:['petition writer','get a village grievance heard']};
export function arrive(s){if(s.chapter<2)return '';s.jianghu.active=null;if(hashSeed(s.seed+':meeting:'+s.revision)%3)return '';const j=s.jianghu,p=province(s);let person=j.people.find(x=>x.region===p.name&&x.place===s.location&&x.lastChapter!==s.chapter);if(!person){if(j.people.some(x=>x.region===p.name&&x.place===s.location))return '';const id=hashSeed(s.seed+':'+p.name+':'+s.location);person={id:String(id),name:['Han','Seo','Min','Baek','Im','Na'][id%6]+' '+['Dami','Gyeol','Harin','Jiseok','Nari','Taesu','Wol','Yejin'][Math.floor(id/6)%8],region:p.name,place:s.location,role:roles[s.location][0],goal:roles[s.location][1],trust:0,memories:[],lastChapter:0};j.people.push(person);j.people=j.people.slice(-64);}person.lastChapter=s.chapter;j.active=person.id;j.serial++;return `${person.name}, a ${person.role}, pauses beside the road. They hope to ${person.goal}.${person.memories.length?' They recognize you from an earlier meeting.':''}`;}
export function jianghuOptions(s){if(s.chapter<2||s.combat||s.ending)return [];const a=[],c=roadContact(s);if(c){a.push({id:'sect:talk',label:'Speak with '+c.npc,detail:'1 turn · learn about '+c.name});if(s.flags['sect-arc:'+c.id]!=='bargain'&&s.jianghu.standing[c.id]>=2&&!Object.hasOwn(s.techniques,c.lesson))a.push({id:'sect:lesson',label:'Learn '+techniques.find(t=>t.id===c.lesson).name,detail:'1 turn · 4 coins · standing 2 · technique attribute 4'});if(!s.flags['sect-service:'+c.id])a.push({id:'sect:serve',label:'Help '+c.name+' shelter travelers',detail:'2 turns · 3 qi · +2 standing, +2 insight · once per sect'});}
if(s.jianghu.active)a.push({id:'meeting:help',label:'Help the traveler',detail:'2 turns · 2 qi · +1 insight and trust'},{id:'meeting:listen',label:'Listen to their story',detail:'1 turn · remember their situation; no material reward'},{id:'meeting:leave',label:'Wish them a safe road',detail:'End this meeting · no cost'});return a;}
export function jianghuAction(s,verb,id,speech='',tone=''){if(!jianghuOptions(s).some(a=>a.id===verb+':'+id))throw Error('That meeting is no longer available.');if(verb==='sect'){const c=roadContact(s);s.flags['sect-known:'+c.id]=true;if(id==='talk'&&speech){s.flags['sect-heard:'+c.id]=String(speech).slice(0,250);s.jianghu.memories[c.id].push('Heard: '+String(speech).slice(0,250));s.jianghu.memories[c.id]=s.jianghu.memories[c.id].slice(-12);const hostile=tone==='hostile'||/\b(threaten|idiot|coward|worthless|hurt you)\b/i.test(speech)&&!/\b(won.t|will not|never|don.t)\b/i.test(speech);const kind=tone==='kind'||/\b(thank|help|trust|protect|understand)\b/i.test(speech);s.flags['sect-mood:'+c.id]=hostile?'hostile':kind?'warm':'neutral';if(hostile&&!s.flags['sect-insult:'+c.id]){s.jianghu.standing[c.id]=Math.max(0,s.jianghu.standing[c.id]-1);s.flags['sect-insult:'+c.id]=true;}}if(id==='talk'&&s.flags['sect-arc:'+c.id]==='bargain')return {time:1,text:`${c.npc}: Public business is still public. My private teaching is closed after what you did with the evidence.`};if(id==='talk'&&s.flags['sect-mood:'+c.id]==='hostile')return {time:1,text:`${c.npc}: ${({crane:'Lower your voice. Threats do not turn an accusation into evidence.',reed:'A boat can carry anger. It cannot carry someone who threatens the crew.',cinder:'You mistake restraint for permission. Do not threaten me again.'})[c.id]}`};if(id==='talk'&&s.flags['sect-mood:'+c.id]==='warm')return {time:1,text:`${c.npc}: ${({crane:'Then help me put the burden where it belongs. The villages have carried enough.',reed:'Good. There is room for another honest pair of hands at the ropes.',cinder:'I hear you. Protect their right to leave, even when our elders call it disloyalty.'})[c.id]}`};if(id==='talk')return {time:1,text:`${c.npc}: “${c.line}” ${c.goal} Within ${c.name}: ${c.dispute}`};if(id==='lesson'){const t=techniques.find(t=>t.id===c.lesson);if(s.coins<4||s.stats[t.stat]<4)throw Error('The lesson needs 4 coins and '+t.stat+' 4.');s.coins-=4;s.techniques[t.id]=0;return {time:1,text:`Because of your service, ${c.npc} teaches ${t.name}. Practice will turn this first lesson into mastery.`};}if(s.qi<3)throw Error('Sheltering travelers needs 3 qi.');s.qi-=3;s.insight+=2;s.jianghu.standing[c.id]+=2;s.flags['sect-service:'+c.id]=true;return {time:2,text:`You help ${c.npc} shelter displaced travelers. ${c.name} standing +2, insight +2. They will remember your service.`};}
const p=s.jianghu.people.find(x=>x.id===s.jianghu.active);if(id==='help'){if(s.qi<2)throw Error('Helping needs 2 qi.');s.qi-=2;s.insight++;p.trust++;}const text=id==='help'?`You help ${p.name} ${p.goal}. +1 insight; their trust grows.`:id==='listen'?`${p.name} tells you why they must ${p.goal}. You learn their circumstances without promising a solution.`:`You part peacefully with ${p.name}.`;p.memories.push(text);p.memories=p.memories.slice(-8);s.jianghu.active=null;return {time:id==='leave'?0:id==='help'?2:1,text};}
export function validateJianghu(s){const j=s.jianghu;if(!j||!Array.isArray(j.people)||j.people.length>64||!Number.isInteger(j.serial)||j.serial<0||sects.some(c=>!Number.isInteger(j.standing?.[c.id])||j.standing[c.id]<0||j.standing[c.id]>4))throw Error('Invalid jianghu history.');for(const c of sects)if(!Array.isArray(j.memories?.[c.id])||j.memories[c.id].length>12||j.memories[c.id].some(m=>typeof m!=='string'||m.length>1000))throw Error('Invalid sect memory.');for(const p of j.people)if(!p||['id','name','region','place','role','goal'].some(k=>typeof p[k]!=='string'||p[k].length>200)||!Number.isInteger(p.trust)||p.trust<0||!Number.isInteger(p.lastChapter)||!Array.isArray(p.memories)||p.memories.length>8||p.memories.some(m=>typeof m!=='string'||m.length>1000))throw Error('Invalid traveler.');if(j.active!==null&&!j.people.some(p=>p.id===j.active))throw Error('Invalid meeting.');}

export const sectMood=(s,c)=>s.flags['sect-arc:'+c.id]==='bargain'?'hostile':s.flags['sect-mood:'+c.id]||(s.flags['sect-arc:'+c.id]==='loyal'?'warm':'neutral');
