import {places} from './world.mjs';
import {prepareCombat} from './combat.mjs';
const names=['Han Suri','Min Jae','Seo Wol','Jin Muro','Yeon Nari','Park Dae','Im Hwan','Su Rina','Baek Jun','Na Eunsol'];
const roles=['disgraced courier','itinerant bone-setter','debt collector','salt broker','escaped apprentice','herbal peddler','ferry widow','wandering scribe'];
const temperaments=['wary','forthright','wry','proud','gentle'];
const templates=[
 {id:'medicine',title:'A bowl worth more than silver',text:'A traveler has medicine but no escort through the quarantine. The price of hesitation is written in the shaking of their hands.',choices:[['escort','Escort them','2 turns · 2 qi · earn 6 coins and trust'],['buy','Buy their spare herb','1 turn · 3 coins · gain an herb'],['rob','Seize the medicine','1 turn · fight their armed companion'],['leave','Let them pass','No reward · this meeting ends']]},
 {id:'debt',title:'Someone else’s debt',text:'A collector pins an unpaid note to a shutter. The named debtor insists the seal was forged. Both turn to you.',choices:[['mediate','Examine the debt','1 turn · Mind 6 for full reward; failure costs 2 coins'],['pay','Pay the debt','1 turn · 5 coins · gain trust and insight'],['fight','Challenge the collector','Fight · reward 7 coins; lose reputation if defeated'],['leave','Decline involvement','No reward · this meeting ends']]},
 {id:'relic',title:'A lesson left in the rain',text:'A damaged training scroll is offered beside a cold brazier. Its owner wants someone to prove the form still has value.',choices:[['study','Study together','2 turns · 3 qi · gain 2 insight'],['trade','Buy a lesson','1 turn · 4 coins · learn a seeded technique'],['spar','Test the owner’s form','Fight a sparring opponent · gain insight on victory'],['leave','Walk on','No reward · this meeting ends']]},
 {id:'rumor',title:'The price of a name',text:'A road agent offers information about the fever shipment. They will take coin, a promise, or a dangerous favor.',choices:[['listen','Trade a careful question','1 turn · Mind 5 reveals convoy evidence'],['promise','Promise safe passage','1 turn · remember a debt; earn trust'],['ambush','Drive off their pursuer','Fight · gain convoy evidence and trust'],['leave','Keep your own counsel','No reward · this meeting ends']]},
 {id:'cache',title:'A door no one claims',text:'A local guide finds an abandoned supply cache. Fresh footprints suggest that abandoned is a matter of opinion.',choices:[['share','Share the supplies','1 turn · 1 herb and local trust'],['take','Take the whole cache','Fight its returning guard · 10 coins and an herb'],['seal','Seal it for the sick','1 turn · gain 2 insight; leave the goods'],['leave','Avoid the dispute','No reward · this meeting ends']]}
];
export function hashSeed(seed){let x=2166136261;for(const c of String(seed))x=Math.imul(x^c.charCodeAt(0),16777619);return x>>>0;}
export function worldFor(seed){let n=hashSeed(seed);const roll=max=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n%max;};const spots=['gate','clinic','market','ferry','forge','shrine','sluice','tribunal'];const order=[...spots];for(let i=order.length-1;i>0;i--){const j=roll(i+1);[order[i],order[j]]=[order[j],order[i]];}const people=Array.from({length:4},(_,i)=>({id:'wanderer-'+i,name:names[(roll(names.length)+i)%names.length]+' '+['of Reedbank','of the Salt Road','of North Pass','of the Low Hills'][i],role:roles[roll(roles.length)],temperament:temperaments[roll(temperaments.length)],home:order[i],destination:order[i+4],moveAt:8+roll(12),trust:0,memories:[],goal:['earn passage before dusk','find a missing sibling','repay a dangerous debt','preserve a teacher’s last lesson'][i]}));const events={};order.forEach((location,i)=>{events[location]={template:templates[roll(templates.length)].id,npc:people[i%4].id,resolved:false,choice:null,expires:18+roll(18),technique:['seal','cinder','echo','tide','smelt','face','grave','meteor'][roll(8)]};});return {seed:String(seed).slice(0,80),people,events};}
export function encounter(s){const e=s.world?.events[s.location];if(!e||e.resolved||s.time-(s.world.startedAt||0)>=e.expires||s.combat||s.ending)return null;const person=s.world.people.find(p=>p.id===e.npc);if((s.time-(s.world.startedAt||0)>=person.moveAt?person.destination:person.home)!==s.location)return null;const template=structuredClone(templates.find(t=>t.id===e.template));if(s.chapter>1&&e.template==='rumor'){template.title='The toll nobody admits';template.text='A road agent has copied two conflicting toll schedules. Someone is charging the same caravan twice; their pursuer wants the copies burned.';template.choices=template.choices.map(c=>c[0]==='listen'?[c[0],c[1],'1 turn · Mind 5 · gain 1 insight from the discrepancy']:c[0]==='ambush'?[c[0],c[1],'Fight · gain trust and an encounter reward']:c);}return {...e,...template,expires:e.expires+(s.world.startedAt||0),npc:s.world.people.find(p=>p.id===e.npc)};}
export function eventChoices(s){const e=encounter(s);return e?e.choices.map(([id,label,detail])=>({id:'event:'+id,label,detail})):[];}
export function resolveEvent(s,id){const e=encounter(s);if(!e||!e.choices.some(c=>c[0]===id))throw Error('That opportunity has passed.');const record=s.world.events[s.location],npc=e.npc;
 const spend=(key,n)=>{if(s[key]<n)throw Error('This choice needs '+n+' '+key+'.');s[key]-=n;};let time=1,reward='';const rep=amount=>{npc.trust+=amount;s.reputation.river+=amount;};
 if(id==='leave'){time=0;reward='You let the meeting end. The road keeps its own counsel.';}
 if(id==='escort'){spend('qi',2);time=2;s.coins+=6;rep(1);reward='You walk the traveler through the checkpoint. +6 coins; a favor remembered.';}
 if(id==='buy'){spend('coins',3);s.inventory.herb++;reward='A sealed herb changes hands. The traveler checks that you know its dosage.';}
 if(id==='mediate'){if(s.stats.mind>=6){s.coins+=5;rep(1);s.insight++;reward='The seal is a copy. You settle the dispute: +5 coins, +1 insight.';}else{spend('coins',Math.min(2,s.coins));reward='The handwriting defeats you. You pay two coins, or what remains, to end the argument.';}}
 if(id==='pay'){spend('coins',5);rep(2);s.insight++;reward='You buy a stranger one free morning. +1 insight; their trust deepens.';}
 if(id==='study'){spend('qi',3);time=2;s.insight+=2;reward='You reconstruct the missing movement together. +2 insight.';}
 if(id==='trade'){if(Object.hasOwn(s.techniques,e.technique))throw Error('You already know the offered form. Study together instead.');spend('coins',4);s.techniques[e.technique]=0;reward='The traveler teaches the first form of '+e.technique+'.';}
 if(id==='listen'){if(s.stats.mind>=5){if(s.chapter===1){s.flags.route=true;reward='You separate rumor from fact: a manifest copy confirms the Court’s diverted convoy.';}else{s.insight++;reward='The duplicate toll entries reveal how travelers are being overcharged. +1 insight.';}}else reward='The story contradicts itself. You learn nothing reliable this time.';}
 if(id==='promise'){s.promises.push('Safe passage promised to '+npc.name);rep(1);reward='They accept your word. A promise is now part of your history.';}
 if(id==='share'){s.inventory.herb++;rep(1);reward='You split the cache fairly. +1 herb; the guide remembers your restraint.';}
 if(id==='seal'){s.insight+=2;s.reputation.bone++;reward='You leave the medicine for those who cannot walk here. +2 insight; Bone Bell reputation +1.';}
 if(['rob','fight','spar','ambush','take'].includes(id)){const spar=id==='spar';s.combat={name:spar?npc.name:'Road '+(id==='fight'?'collector':'guard'),hp:spar?24:28,maxHp:spar?24:28,turn:0,intent:spar?'quick':'heavy',event:true,reward:id,npc:npc.id};prepareCombat(s.combat,spar?'duelist':'warden');reward=(spar?'A respectful test begins.':'Steel leaves its sheath.')+(s.chapter===1?' This encounter does not grant the main ledger.':'');if(id==='rob'||id==='take')s.reputation.jade--;}
 record.resolved=true;record.choice=id;npc.memories.push('At turn '+s.time+', the traveler chose to '+id+'.');npc.memories=npc.memories.slice(-10);return {time,text:npc.name+', '+npc.role+': '+reward};
}
export function eventVictory(s,c){const npc=s.world.people.find(p=>p.id===c.npc);s.insight+=c.reward==='spar'?2:1;s.coins+=c.reward==='take'?10:c.reward==='fight'?7:c.reward==='spar'?0:4;if(c.reward==='rob'||c.reward==='take')s.inventory.herb++;if(c.reward==='ambush'){if(s.chapter===1)s.flags.route=true;npc.trust++;}npc.memories.push('The traveler won a '+c.reward+' encounter.');return `${c.name} yields. ${c.reward==='spar'?'The lesson grants 2 insight.':'You claim the encounter reward and 1 insight.'}${s.chapter===1?' The fever ledger is still a separate matter.':''}`;}
export function worldTick(s,before,landmarks=places){const lines=[];for(const p of s.world?.people||[]){if(before-(s.world.startedAt||0)<p.moveAt&&s.time-(s.world.startedAt||0)>=p.moveAt){p.memories.push('Moved to '+landmarks[p.destination].name+' to '+p.goal+'.');lines.push(p.name+' leaves '+landmarks[p.home].name+' for '+landmarks[p.destination].name+' to '+p.goal+'.');}}return lines;}
