import {threatTier} from './growth.mjs';
import {currentRegion} from './regions.mjs';
import {prepareCombat} from './combat.mjs';
import {worldFor,hashSeed} from './procedural.mjs';
const names=['Black Reed','Fallen Plum','Cinder Ford','White Heron','Broken Moon','Nine Wells','Quiet Thunder','Red Willow'];
export const approaches={
 observe:{name:'Observe / investigate',stat:'mind',cost:1,risk:0,desc:'Read tracks, inspect a scene, question a rumor. Insight on success.'},
 persuade:{name:'Persuade / negotiate',stat:'mind',cost:1,risk:0,desc:'Make a case or negotiate cooperation. Gain local standing on success.'},
 craft:{name:'Craft / repair',stat:'mind',cost:2,risk:0,desc:'Make a practical supply or repair ordinary equipment. Costs 2 coins; an herb-equivalent supply on success.'},
 sneak:{name:'Sneak / steal',stat:'fate',cost:1,risk:3,desc:'Attempt a covert approach. Coin on success, injury and reputation loss on failure.'},
 aid:{name:'Aid / protect',stat:'spirit',cost:2,risk:0,desc:'Help with practical work or care. Costs 2 qi; gain insight and standing on success.'},
 labor:{name:'Work / trade',stat:'body',cost:2,risk:0,desc:'Spend two turns earning coin. Always earns a small wage; skill improves it.'},
 challenge:{name:'Challenge / fight',stat:'body',cost:1,risk:0,desc:'Begin a generated road duel. Opponent strength rises modestly on later roads.'},
 social:{name:'Talk / connect',stat:'mind',cost:1,risk:0,desc:'Spend time with people nearby. Record the meeting; standing on success.'}
};
export function regionName(s){return s.chapter>1?names[s.regionIndex??hashSeed(s.seed+':'+s.chapter)%names.length]+' District': 'Rainbound Valley';}
export function continueJourney(previous,target){const s=structuredClone(previous);if(s.ending==='death')throw Error('This traveler has died. Begin another life.');if(!s.ending)throw Error('Finish this chapter before continuing.');s.chapters=s.chapters||[];s.chapters.push({chapter:s.chapter||1,outcome:s.ending,time:s.time,region:regionName(s)});s.chapters=s.chapters.slice(-40);s.chapter=(s.chapter||1)+1;if(target===undefined)delete s.regionIndex;else s.regionIndex=target;s.ending=null;s.flags.secondHeart=false;for(const key of Object.keys(s.flags))if(key.startsWith('search:'))delete s.flags[key];s.contacts={...(s.contacts||{}),...Object.fromEntries(s.world.people.map(p=>[s.world.seed+':'+p.id,structuredClone(p)]))};s.contacts=Object.fromEntries(Object.entries(s.contacts).slice(-80));s.world=worldFor(s.seed+':road:'+s.chapter);s.world.startedAt=s.time;s.location='gate';s.combat=null;if(s.jianghu)s.jianghu.active=null;s.quests.road='Choose your own purpose in '+regionName(s)+'. Encounters are optional; work, explore, train or move on.';s.journal.push({time:s.time,turn:s.revision+1,kind:'story',text:'The road does not end at the valley gate. You arrive in '+regionName(s)+', carrying your techniques, scars, promises and reputation. New travelers pursue their own business here. Your next purpose belongs to you.'});s.journal=s.journal.slice(-120);s.revision++;return s;}
export function nextRoad(previous,target){if((previous.chapter||1)<2)throw Error('Conclude the valley chapter first, or choose its wandering ending.');const s=structuredClone(previous);s.ending='wander';return continueJourney(s,target);}
export function sandboxOptions(s){return Object.entries(approaches).map(([id,a])=>({id:'improvise:'+id,label:a.name,detail:id==='challenge'?`Begin road combat · tier ${threatTier(s)} · ${24+Math.min(12,(s.chapter-1)*2)+threatTier(s)*4} health. ${threatTier(s)>=2?'Deadly: defeat with two untreated wounds means death.':'Defeat causes a serious wound.'}`:a.desc}));}
export function resolveImprovisation(s,id,text){const a=approaches[id];if(!a)throw Error('Choose an approach.');const input=String(text||a.name).trim().slice(0,1000);if(id==='craft'&&s.coins<2)throw Error('Crafting needs 2 coins.');if(id==='aid'&&s.qi<2)throw Error('Aid needs 2 qi.');if(id==='craft')s.coins-=2;if(id==='aid')s.qi-=2;
 const roll=1+hashSeed(s.seed+':'+s.revision+':'+id)%6;const difficulty=8+Math.min(3,Math.floor(((s.chapter||1)-1)/3));const total=s.stats[a.stat]+roll+Math.min(2,s.cultivation);const success=total>=difficulty;
 let outcome='';
 if(id==='challenge'){const hp=24+Math.min(12,((s.chapter||1)-1)*2);s.combat={name:['Wandering swordsman','Road warden','Disgraced disciple','Traveling spear adept'][hashSeed(s.seed+s.revision)%4],hp,maxHp:hp,turn:0,intent:['heavy','quick','guard'][hashSeed(s.seed+':intent:'+s.revision)%3],sandbox:true};prepareCombat(s.combat,['duelist','warden','disciple','spear'][hashSeed(s.seed+s.revision)%4]);outcome='A road opponent accepts your challenge. Combat begins; victory is not assured.';}
 else if(id==='labor'){const marketBonus=currentRegion(s)?.prosperity>=60?1:0;const wage=(success?5:2)+marketBonus;s.coins+=wage;outcome='You earn '+wage+' coins for the time spent.';}
 else if(success){if(id==='observe'||id==='aid')s.insight++;if(id==='craft')s.inventory.herb=Math.min(100,(s.inventory.herb||0)+1);if(id==='sneak')s.coins+=4;if(['persuade','social','aid'].includes(id))s.reputation.river++;outcome={observe:({gate:'You study how travelers shift their weight before changing direction.',clinic:'You notice how arranging bandages before treatment saves the healer time.',market:'You compare posted prices and see how river tolls affect freight costs.',ferry:'You study how a mooring knot distributes strain.',forge:'You watch the smith adjust airflow to steady the furnace heat.',shrine:'You match a slow breathing rhythm to the bell fading away.',sluice:'You study the current slowing behind a closed water gate.',tribunal:'You notice how a clear sequence of events makes testimony easier to follow.'}[s.location]+' +1 insight.'),persuade:'Your case earns a hearing. +1 local standing.',craft:'You finish a useful field remedy. +1 herb.',sneak:'You secure four unguarded coins. Someone may still notice.',aid:'Your help makes a difference. +1 insight and local standing.',social:'The conversation opens a door. +1 local standing.'}[id];}
 else{if(a.risk){s.hp=Math.max(1,s.hp-a.risk);s.reputation.jade--;}outcome='The attempt meets resistance. '+(a.risk?'You escape with a minor injury: −3 health, Court reputation −1.':'The time and committed resources are spent, but you gain no reward.');}
 s.facts.push('At turn '+s.time+' in '+regionName(s)+', attempted: '+input+'. Result: '+outcome);s.facts=s.facts.slice(-180);return {practice:success&&!['challenge','social','persuade'].includes(id)?a.stat:null,time:a.cost,text:`${input}\n${id==='challenge'?'':`${a.stat.toUpperCase()} ${s.stats[a.stat]} + roll ${roll} + cultivation ${Math.min(2,s.cultivation)} vs ${difficulty}: ${success?'success':'setback'}. `}${outcome}`};}
